	<div class="footer">
        <div class="link-about clearfix">
            <div class="line">
                <div class="logo logo-small"><a href="javascript:void(0);" title="P2PBUY">P2PBUY</a></div>
            </div>
            <dl class="line">
                <dt class="tit">新手指南</dt>
                <dd class="list">
                    <div><a href="javascript:void(0);">购买流程</a></div>
                    <div><a href="javascript:void(0);">支付方式</a></div>
                    <div><a href="javascript:void(0);">配送方式</a></div>
                </dd>
            </dl>
            <dl class="line">
                <dt class="tit">购物保障</dt>
                <dd class="list">
                    <div><a href="javascript:void(0);">正品保证</a></div>
                    <div><a href="javascript:void(0);">海外直购</a></div>
                    <div><a href="javascript:void(0);">物流说明</a></div>
                </dd>
                <dd class="list second">
                    <div><a href="javascript:void(0);">通关关税</a></div>
                    <div><a href="javascript:void(0);">常见问题</a></div>
                    <div><a href="javascript:void(0);">联系客服</a></div>
                </dd>
            </dl>
            <dl class="line">
                <dt class="tit">关于我们</dt>
                <dd class="list">
                    <div><a href="javascript:void(0);">网站介绍</a></div>
                    <div><a href="javascript:void(0);">加入我们</a></div>
                    <div><a href="javascript:void(0);">商务合作</a></div>
                </dd>
            </dl>
            <div class="line"><a href="javascript:void(0);" class="other"><img src="http://<?=$domain['res']?>/img/_temp/u114.jpg" alt=""></a></div>
            <div class="line"><a href="javascript:void(0);" class="other"><img src="http://<?=$domain['res']?>/img/_temp/u116.jpg" alt=""></a></div>
        </div>
        <p>Copyright © 2014 P2PBUY.INC.  All Rights Reserved  使用本网站即表示接受用户协议</p>
        <p>P2PBUY 版权所有 京ICP备20080101</p>
    </div>