	<div class="header">
        <div class="top-bar">
            <div class="inner">
                <div class="login-info">
                    <!--未登录状态-->
                    <ul class="inline unlogin" style="display:none">
                        <li><a href="#">登录</a></li>
                        <li><a href="/reg/reg">注册</a></li>
                    </ul>
                    <!--/未登录状态-->
                    <!--已登录状态-->
                    <ul class="inline logined" style="display:">
                    	<li><a href="/order/myorder" target="_blank">我的订单</a></li>
                        <li class="message"><a href="#" title="我是买手"><span>我是买手</span></a></li>
                        <li class="user"><a href="#" ><span class=""><?=$nick?></span></a></li>
                        <li class="opt"><a href="/login/logout" ><span class="">退出</span></a></li>
                    </ul>      
                    <!--/已登录状态-->
                </div>
            </div>
        </div>

        <dl class="head-wrap clearfix">
            <dt class="logo logo-small"><a href="" title="P2PBUY">P2PBUY</a></dt>
            <dd class="search-box">
                <div><input type="text" class="search-input" placeholder="直接粘贴海外商品网址"><a href="#" class="btn btn-primary" title="一键海淘">一键海淘</a></div>
                <a href="" class="nolink">找不到链接？传张图片也能买！</a>
            </dd>
        </dl>
    </div>