<div id="header">
	<ul id="header_left">
		<div id="logo"><li><a href="#">带购</a></li></div>
		<li><a href="#">手机代购</a></li>
		<li><a href="#">海淘梯子</a></li>
		<li><a href="#">社区</a></li>
	</ul>
	<ul id="header_right">
		<?php if($islogined == true):?><li><a href="/login/logout"><?=_('退出登录')?></a></li><?php endif;?>
		<li><a href="#">帮助中心</a></li>
		<li><a href="#"><?=$usertype?></a></li>
		<li><a href="/order/myorder" target="_blank">我的订单</a></li>
		<li><a href="#"><?=$nick?></a></li>
		<?php if($islogined == false):?><li><a href="/login/login"><?=_('登录')?></a></li><?php endif;?>
	</ul>
</div>
