<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?=_('登录')?></title>
</head>
<body>
<form action="/aj/login" method="post">
邮箱：<input name="email" type="text" /></br>
密码：<input name="passwd" type="password" /></br>
<input type="submit" value="login now" />
</form>
</body>

</html>