<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
<meta charset="utf-8">
<title>人民海淘-商品解析页</title>
<meta name="description" content="P2PBUY">
<link href="http://res.p2pbuy.net/css/module/combine.css" rel="stylesheet">
<link href="http://res.p2pbuy.net/css/page/goods-detail.css" rel="stylesheet">
<link href="http://res.p2pbuy.net/css/module/layer-login.css" rel="stylesheet">
</head>

<body class="P-goods-detail">
	
	<div class="header">
		<?php include TPL_PATH."/comm/header.phtml"?>
		<dl class="head-wrap clearfix">
            <dt class="logo logo-small"><a href="" title="P2PBUY">P2PBUY</a></dt>
            <dd class="search-box">
                <div><input type="text" class="search-input" placeholder="直接粘贴海外商品网址"><a href="#" class="btn btn-primary" title="一键海淘">一键海淘</a></div>
                <a href="" class="nolink">找不到链接？传张图片也能买！</a>
            </dd>
        </dl>
    </div>

    <div class="main-content" id="ordering_form">
        <!--购买进度-->
        <div class="step-trilogy">
            <div class="inner">
                <a href="#" class="step cur"><span>1.提交商品网址</span></a>
                <a href="#" class="step"><span>2.确认订单</span></a>
                <a href="#" class="step"><span>3.支付费用</span></a>
                <a href="#" class="step"><span>4.交易完成</span></a>
            </div>
            <?php if($thirdurl):?>
            <dl class="url-info clearfix">
                <dt class="tit">您提交的网址为：</dt>
                <dd class="detail"><a href="<?=$thirdurl?>" target="_blank"><?=$thirdurl?></a></dd>
            </dl>
            <?php endif;?>
        </div>
        <!--/购买进度-->
        
        <?php if($thirdurl):?>
        <iframe src="/order/getiframe?thirdurl=<?=urldecode($thirdurl)?>" frameborder="0" width="1000" height="1000"></iframe>
        <?php endif;?>
        <div class="info-box iframe-info">
        	<form onsubmit="return false;" id="createOrder">
            <!-- <div class="con-item">
            	<dl class="other-info clearfix">
                	<dt class="tit">订单标题：</dt>
                	<dd class="cont"><input name="title" node-type="title" type="text" class="amount-input" maxlength="8" title="请输入购买量"></dd>
                </input>
            </div>
           <div class="con-item">
                <dl class="other-info clearfix">
                    <dt class="tit">商品描述：</dt>
                    <dd class="cont"><textarea name="description" node-type="description" rows="2" placeholder="商品描述"></textarea></dd>
                </dl>
            </div>
             -->
            <div class="con-item">
                <dl class="other-info clearfix">
                    <dt class="tit">数量</dt>
                    <dd class="cont">
                        <span class="amount-wrap">
                            <span class="amount-opt">
                                <!-- <span class="amount-decrease" title="减一">-</span> -->
                                <input name="quantity" node-type="quantity" type="text" class="amount-input" value="1" maxlength="8" title="请输入购买量">
                                <!-- <span class="amount-increase" title="加一">+</span> -->
                            </span>
                            <span class="amount-unit">件</span>
                        </span>
                    </dd>
                </dl>
            </div>
            <div class="con-item">
                <dl class="other-info clearfix">
                    <dt class="tit">备注：</dt>
                    <dd class="cont"><textarea name="additional" rows="2" placeholder="如果有特殊要求请在此填写（如颜色、尺码等），十分重要，请务必正确填写。"></textarea></dd>
                </dl>
            </div>
            <!-- <div class="con-item">
            	<dl class="other-info clearfix">
            		<dt class="tit">图片：</dt>
            		<dd class="cont"><input type="file" name="file" value="上传附件">请使用jpg，gif，png图片，大小请不要超过1MB<br></dd>
            	</dl>
            </div>
             -->
			<input type="hidden" name="thirdurl" value="<?=$thirdurl?>"/>
            <div class="btn-box">
                <a href="javascript:void(0);" class="btn btn-warning" action-type="createBuyOrder">立即购买</a>
            </div>
            </form>
        </div>
        
    </div>

	<!-- 登录层 -->
	<div class="modal layer-login " id="layer_login" style="display:none">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true" action-type="closeLayer">&times;</button>
            <h4>登录P2PBUY</h4>
        </div>
        <div class="modal-body row-fluid">
            <div class="span5">
                <h5>没有账号？请立即申请</h5>
                <a href="javascript:void(0);" class="btn" action-type="showRegLayer">立即注册</a>
            </div>
            <div class="span7">
                <form class="form-horizontal" onsubmit="return false;">
                    <div class="control-group">
                        <label class="control-label" for="inputEmail">账号</label>
                        <div class="controls input-prepend">
                            <span class="add-on"><i class="icon-user"></i>
                            </span>
                            <input class="input-medium" id="prependedInput" type="text" placeholder="邮箱/手机号" node-type="username">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="inputEmail">密码</label>
                        <div class="controls input-prepend">
                            <span class="add-on"><i class="icon-lock"></i>
                            </span>
                            <input class="input-medium" id="prependedInput" type="password" placeholder="输入您的密码" node-type="passwd">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="inputEmail">&nbsp;</label>
                        <div class="controls box-btn">
                            <button type="submit" class="btn" action-type="login">登录</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- 登录层 -->
    
    <!-- 注册层 -->
    <div class="modal layer-login " id="layer_reg" style="display:none">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true" action-type="closeLayer">&times;</button>
            <h4>注册P2PBUY</h4>
        </div>
        <div class="modal-body row-fluid">
            <div class="span5">
                <h5>已经有账号？请立即登录</h5>
                <a href="javascript:void(0);" class="btn" action-type="showLoginLayer">立即登录</a>
            </div>
            <div class="span7">
                <form class="form-horizontal" onsubmit="return false;">
                    <div class="control-group">
                        <label class="control-label" for="inputEmail">账号</label>
                        <div class="controls input-prepend">
                            <span class="add-on"><i class="icon-user"></i>
                            </span>
                            <input class="input-medium" id="prependedInput" type="text" placeholder="邮箱/手机号" node-type="username_reg">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="inputEmail">密码</label>
                        <div class="controls input-prepend">
                            <span class="add-on"><i class="icon-lock"></i>
                            </span>
                            <input class="input-medium" id="prependedInput" type="password" placeholder="输入您的密码" node-type="passwd_reg">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="inputEmail">昵称</label>
                        <div class="controls input-prepend">
                            <span class="add-on"><i class="icon-user"></i>
                            </span>
                            <input class="input-medium" id="prependedInput" type="text" placeholder="昵称" node-type="nick">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="inputEmail">&nbsp;</label>
                        <div class="controls box-btn">
                            <button type="submit" class="btn" action-type="reg">注册</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- 注册层 -->
	<?php include TPL_PATH."/comm/footer.phtml"?>
    
<script src="http://res.p2pbuy.net/js/jquery-1.11.1.min.js"></script>
<script src="http://res.p2pbuy.net/js/common.js"></script>
<script src="http://res.p2pbuy.net/js/order/buy.js"></script>

</body>
</html>
