<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
<meta charset="utf-8">
<title>商品解析页</title>
<meta name="description" content="P2PBUY">
<link href="http://res.p2pbuy.net/css/module/combine.css" rel="stylesheet">
<link href="http://res.p2pbuy.net/css/page/goods-detail.css" rel="stylesheet">
</head>

<body class="P-goods-detail">

    <div class="header">
        <div class="top-bar">
            <div class="inner">
                <div class="login-info">
                    <!--未登录状态-->
                    <ul class="inline unlogin" style="display:none">
                        <li><a href="#">登录</a></li>
                        <li><a href="">注册</a></li>
                    </ul>
                    <!--/未登录状态-->
                    <!--已登录状态-->
                    <ul class="inline logined" style="display:">
                    	<li><a href="/order/myorder" target="_blank">我的订单</a></li>
                        <li class="message"><a href="" title="我是买手"><span>我是买手</span></a></li>
                        <li class="user"><a href="" ><span class="">香稻老农</span></a></li>
                        <li class="opt"><a href="" ><span class="">退出</span></a></li>
                    </ul>      
                    <!--/已登录状态-->
                </div>
            </div>
        </div>

        <dl class="head-wrap clearfix">
            <dt class="logo logo-small"><a href="" title="P2PBUY">P2PBUY</a></dt>
            <dd class="search-box">
                <div><input type="text" class="search-input" placeholder="直接粘贴海外商品网址"><a href="" class="btn btn-primary" title="一键海淘">一键海淘</a></div>
                <a href="" class="nolink">找不到链接？传张图片也能买！</a>
            </dd>
        </dl>
    </div>

    <div class="main-content" id="ordering_form">
        <!--购买进度-->
        <div class="step-trilogy">
            <div class="inner">
                <a href="#" class="step cur"><span>1.提交商品网址</span></a>
                <a href="#" class="step"><span>2.确认订单</span></a>
                <a href="#" class="step"><span>3.支付费用</span></a>
                <a href="#" class="step"><span>4.交易完成</span></a>
            </div>
            <?php if($thirdurl):?>
            <dl class="url-info clearfix">
                <dt class="tit">您提交的网址为：</dt>
                <dd class="detail"><a href="<?=$thirdurl?>" target="_blank"><?=$thirdurl?></a></dd>
            </dl>
            <?php endif;?>
        </div>
        <!--/购买进度-->
        
        <?php if($thirdurl):?>
        <iframe src="/order/getiframe?thirdurl=<?=urldecode($thirdurl)?>" frameborder="0" width="1000" height="1000"></iframe>
        <?php endif;?>
        <div class="info-box iframe-info">
        	<form onsubmit="return false;" id="createOrder">
            <div class="con-item">
            	<dl class="other-info clearfix">
                	<dt class="tit">订单标题：</dt>
                	<dd class="cont"><input name="title" node-type="title" type="text" class="amount-input" maxlength="8" title="请输入购买量"></dd>
                </input>
            </div>
           <div class="con-item">
                <dl class="other-info clearfix">
                    <dt class="tit">商品描述：</dt>
                    <dd class="cont"><textarea name="description" node-type="description" rows="2" placeholder="商品描述"></textarea></dd>
                </dl>
            </div>
            <div class="con-item">
                <dl class="other-info clearfix">
                    <dt class="tit">数量</dt>
                    <dd class="cont">
                        <span class="amount-wrap">
                            <span class="amount-opt">
                                <!-- <span class="amount-decrease" title="减一">-</span> -->
                                <input name="quantity" node-type="quantity" type="text" class="amount-input" value="1" maxlength="8" title="请输入购买量">
                                <!-- <span class="amount-increase" title="加一">+</span> -->
                            </span>
                            <span class="amount-unit">件</span>
                        </span>
                    </dd>
                </dl>
            </div>
            <div class="con-item">
                <dl class="other-info clearfix">
                    <dt class="tit">备注：</dt>
                    <dd class="cont"><textarea name="additional" rows="2" placeholder="如果有特殊要求请您在此填写"></textarea></dd>
                </dl>
            </div>
            <div class="con-item">
            	<dl class="other-info clearfix">
            		<dt class="tit">图片：</dt>
            		<dd class="cont"><input type="file" name="file" value="上传附件">请使用jpg，gif，png图片，大小请不要超过1MB<br></dd>
            	</dl>
            </div>
			<input type="hidden" name="thirdurl" value="<?=$thirdurl?>"/>
            <div class="btn-box">
                <a href="javascript:void(0);" class="btn btn-warning" action-type="createBuyOrder">立即购买</a>
            </div>
            </form>
        </div>
        
    </div>

    <div class="footer">
        <div class="link-about clearfix">
            <div class="line">
                <div class="logo logo-small"><a href="#" title="P2PBUY">P2PBUY</a></div>
            </div>
            <dl class="line">
                <dt class="tit">新手指南</dt>
                <dd class="list">
                    <div><a href="">购买流程</a></div>
                    <div><a href="">支付方式</a></div>
                    <div><a href="">配送方式</a></div>
                </dd>
            </dl>
            <dl class="line">
                <dt class="tit">购物保障</dt>
                <dd class="list">
                    <div><a href="">正品保证</a></div>
                    <div><a href="">海外直购</a></div>
                    <div><a href="">物流说明</a></div>
                </dd>
                <dd class="list second">
                    <div><a href="">通关关税</a></div>
                    <div><a href="">常见问题</a></div>
                    <div><a href="">联系客服</a></div>
                </dd>
            </dl>
            <dl class="line">
                <dt class="tit">关于我们</dt>
                <dd class="list">
                    <div><a href="">网站介绍</a></div>
                    <div><a href="">加入我们</a></div>
                    <div><a href="">商务合作</a></div>
                </dd>
            </dl>
            <div class="line"><a href="" class="other"><img src="http://www.p2pbuy.net/img/_temp/u114.jpg" alt=""></a></div>
            <div class="line"><a href="" class="other"><img src="http://www.p2pbuy.net/img/_temp/u116.jpg" alt=""></a></div>
        </div>
        <p>Copyright © 2014 P2PBUY.INC.  All Rights Reserved  使用本网站即表示接受用户协议</p>
        <p>P2PBUY 版权所有 京ICP备20080101</p>
    </div>
    
<script src="http://res.p2pbuy.net/js/jquery-1.11.1.min.js"></script>
<script src="http://res.p2pbuy.net/js/common.js"></script>
<script src="http://res.p2pbuy.net/js/order/buy.js"></script>

</body>
</html>
