<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>提交订单</title>
<meta name="description" content="P2PBUY">
<link href="http://res.p2pbuy.net/css/module/combine.css" rel="stylesheet">
<link href="http://res.p2pbuy.net/css/page/order-submit.css" rel="stylesheet">
</head>

<body class="P-order-submit">

    <div class="header">
        <div class="top-bar">
            <div class="inner">
                <div class="login-info">
                    <!--未登录状态-->
                    <ul class="inline unlogin" style="display:none">
                        <li><a href="#">登录</a></li>
                        <li><a href="">注册</a></li>
                    </ul>
                    <!--/未登录状态-->
                    <!--已登录状态-->
                    <ul class="inline logined" style="display:">
                        <li class="message"><a href="" title="我是买手"><span>我是买手</span></a></li>
                        <li class="user"><a href="" ><span class="">香稻老农</span></a></li>
                        <li class="opt"><a href="" ><span class="">退出</span></a></li>
                    </ul>      
                    <!--/已登录状态-->
                </div>
            </div>
        </div>

        <dl class="head-wrap clearfix">
            <dt class="logo logo-small"><a href="" title="P2PBUY">P2PBUY</a></dt>
            <dd class="search-box">
                <div><input type="text" class="search-input" placeholder="直接粘贴海外商品网址"><a href="" class="btn btn-primary" title="一键海淘">一键海淘</a></div>
                <a href="" class="nolink">找不到链接？传张图片也能买！</a>
            </dd>
        </dl>
    </div>

    <div class="main-content">
        <!--购买进度-->
        <div class="step-trilogy">
            <div class="inner">
                <a href="#" class="step"><span>1.提交商品网址</span></a>
                <a href="#" class="step cur"><span>2.确认订单</span></a>
                <a href="#" class="step"><span>3.支付费用</span></a>
                <a href="#" class="step"><span>4.交易完成</span></a>
            </div>
        </div>
        <!--/购买进度-->
        <div class="order-info">
            <div class="item delivery-address">
                <h3 class="title">选择收货地址</h3>
                <div class="address-box" id="address-box">
                    <ul class="inline clearfix">
                    	<?php foreach($addressInfos as $addressInfo):?>
                    	<?php $i++;?>
                    	<li class="buyer-info <?php if($i == 1):?>choosed<?php endif;?>" action-type="chooseAddress" node-type="chooseAddress">
                            <div class="name"><span class="n1"><?=$addressInfo['country']?> <?=$addressInfo['province']?> <?=$addressInfo['city']?></span><span class="n2">（<?=$addressInfo['name']?> 收）</span></div>
                            <div class="other"><span class="address"><?=$addressInfo['address']?></span><span class="phone"><?=$addressInfo['mobile']?></span></div>
                            <div class="markup"></div>
                        </li>
                    	<?php endforeach;?>
                    </ul>
                </div>
                <div class="add-address" id="add-address">
                    <div class="tit"><a href="javascript:void(0);" action-type="showNewAddr">使用新地址</a></div>
                    <form onsubmit="return false;" class="form-horizontal add-new" node-type="ShowNewAddr" style="display:none">
                        <div class="control-group receipt-name">
                            <label class="control-label" for="inputName">收货人:</label>
                            <div class="controls">
                                <input type="text" id="inputName" placeholder="收货人姓名" node-type="name">
                            </div>
                        </div>
                        <div class="control-group receipt-address">
                            <label class="control-label" for="inputAddress">所在地区:</label>
                            <div class="controls">
                                <select class="pc" node-type="country">
                                	<option value="">选择国家</option>
                                    <option value="中国">中国</option>
                                </select>
                                <select class="pp" node-type="province">
                                    <option value="">选择省份</option>
									<option value="北京">北京</option>
                                </select>
                                <!-- <select class="ca">
                                    <option>选择地区</option>
                                    <option>美国</option>
                                    <option>日本</option>
                                </select> -->
                                <select class="cc" node-type="city">
                                    <option value="">选择县市</option>
									<option value="东城区">东城区</option>
									<option value="西城区">西城区</option>
									<option value="宣武区">宣武区</option>
									<option value="崇文区">崇文区</option>
                                </select>
                            </div>
                        </div>
                        <div class="control-group receipt-detail">
                            <label class="control-label" for="inputDetail">详细地址:</label>
                            <div class="controls">
                                <textarea rows="2" node-type="addrDrtail"></textarea>
                            </div>
                        </div>
                        <div class="control-group receipt-phone">
                            <label class="control-label" for="inputPhone">手机号码:</label>
                            <div class="controls">
                                <input type="text" id="inputPhone" placeholder="收货人电话" node-type="mobile">
                            </div>
                        </div>
                        <!-- <div class="control-group receipt-email">
                            <label class="control-label" for="inputEmail">电子邮箱:</label>
                            <div class="controls">
                                <input type="text" id="inputEmail" placeholder="收货人邮箱">
                            </div>
                        </div> -->
                        <div class="control-group receipt-submit">
                            <div class="controls">
                                <button class="btn btn-primary" action-type="setAddress">确认添加</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="item goods-price">
                <h3 class="title">确认订单信息</h3>
                <div class="info-form">
                    <div class="head-info">
                        <ul class="thead inline clearfix">
                            <li class="th th-name"><i class="shop-amazon"></i><span class="shop-name">亚马逊美国</span></li>
                            <li class="th th-price">价格（元）</li>
                            <li class="th th-amount">数量</li>
                            <li class="th th-offer">优惠（元）</li>
                            <li class="th th-total">小计（元）</li>
                        </ul>
                    </div>
                    <div class="content-info">
                        <div class="goods-table">
                            <ul class="item-main inline clearfix">
                                <li class="td td-chk"><input class="" id="112323" type="checkbox" name="items" value=""></li>
                                <li class="td td-pic"><a href=""><img src="<?=$curBuyOrderInfo['img']?>" alt=""></a></li>
                                <li class="td td-intro">
                                    <p class="name"><?=$curBuyOrderInfo['title']?></p>
                                    <!-- <div class="size"><em>型号</em> <span>“Small ,Bonsai Green”</span></div> -->
                                </li>
                                <li class="td td-price">
                                    <div class="num"><?=$bidprice?></div>
                                </li>
                                <li class="td td-amount">
                                    <div class="num"><?=$curBuyOrderInfo['quantity']?></div>
                                </li>
                                <li class="td td-offer">
                                    <div lass="num">无优惠</div>
                                </li>
                                <li class="td td-total">
                                    <div class="num"><?=$bidprice?></div>
                                </li>
                            </ul>
                            <!-- 
                            <ul class="item-sub inline clearfix">
                                <li class="td td-chk">---</li>
                                <li class="td td-pic">---</li>
                                <li class="td td-intro">
                                   <div class="">优惠码：B00KC2SJHC</div>
                                </li>
                                <li class="td td-price">
                                    <div class="num">---</div>
                                </li>
                                <li class="td td-amount">
                                    <div class="num">1</div>
                                </li>
                                <li class="td td-offer">
                                    <div lass="num">省：300</div>
                                </li>
                                <li class="td td-total">
                                    <div class="num">-300</div>
                                </li>
                            </ul>
                            <ul class="item-sub inline clearfix">
                                <li class="td td-chk">---</li>
                                <li class="td td-pic">---</li>
                                <li class="td td-intro">
                                   <div class="">服务费</div>
                                </li>
                                <li class="td td-price">
                                    <div class="num">179.4</div>
                                </li>
                                <li class="td td-amount">
                                    <div class="num">1</div>
                                </li>
                                <li class="td td-offer">
                                    <div lass="num">满100减10元，省10元</div>
                                </li>
                                <li class="td td-total">
                                    <div class="num">-169.4</div>
                                </li>
                            </ul>
                             -->
                        </div>
                        <div class="goods-total clearfix">
                            <div class="W-fl S-txt2"><em class="tit">补充说明</em><span class="cont"><?=$curBuyOrderInfo['description']?></span></div>
                            <div class="W-fr">
                                <em class="S-txt2">合计（不含运费及关税）：</em><span class="total-price S-txt5">￥<?=$bidprice?></span>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="item goods-cost">
                <h3 class="title">运费及关税信息</h3>
                <div class="info-form">
                    <div class="head-info">
                        <ul class="thead inline clearfix">
                            <li class="th th-name">花费</li>
                            <li class="th th-weight">重量（磅）</li>
                            <li class="th th-type">类型</li>
                            <li class="th th-price">价格（元）</li>
                            <li class="th th-offer">优惠（元）</li>
                            <li class="th th-total">小计（元）</li>
                        </ul>
                    </div>
                    <div class="content-info">
                        <div class="cost-table">
                            <ul class="item-main inline clearfix">
                                <li class="td td-name">商品运费</li>
                                <li class="td td-weight">1.4</li>
                                <li class="td td-type">鞋服，首磅30，续重30</li>
                                <li class="td td-price">60.00</li>
                                <li class="td td-offer">B2BBUY7折，省18</li>
                                <li class="td td-total">42.00</li>
                            </ul>
                            <ul class="item-sub inline clearfix">
                                <li class="td td-name">关税</li>
                                <li class="td td-weight">---</li>
                                <li class="td td-type">奢侈品，关税比例200%</li>
                                <li class="td td-price">3588.00</li>
                                <li class="td td-offer"><em class="W-fb S-txt5">关税补贴，省3588.00</em></li>
                                <li class="td td-total">00.00</li>
                            </ul>
                        </div>
                        <div class="cost-total clearfix">
                            <div class="W-fl S-txt2"></div>
                            <div class="W-fr">
                                <em class="W-fb S-txt5">运费和关税均为估值，需要收到商品后按照实际重量计算</em><span class="total-price S-txt2">￥1663.40</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item goods-settlement">
                <a href="" class="btn btn-primary">提交订单</a>
            </div>
        </div>
        
       
    </div>

    <div class="footer">
        <div class="link-about clearfix">
            <div class="line">
                <div class="logo logo-small"><a href="#" title="P2PBUY">P2PBUY</a></div>
            </div>
            <dl class="line">
                <dt class="tit">新手指南</dt>
                <dd class="list">
                    <div><a href="">购买流程</a></div>
                    <div><a href="">支付方式</a></div>
                    <div><a href="">配送方式</a></div>
                </dd>
            </dl>
            <dl class="line">
                <dt class="tit">购物保障</dt>
                <dd class="list">
                    <div><a href="">正品保证</a></div>
                    <div><a href="">海外直购</a></div>
                    <div><a href="">物流说明</a></div>
                </dd>
                <dd class="list second">
                    <div><a href="">通关关税</a></div>
                    <div><a href="">常见问题</a></div>
                    <div><a href="">联系客服</a></div>
                </dd>
            </dl>
            <dl class="line">
                <dt class="tit">关于我们</dt>
                <dd class="list">
                    <div><a href="">网站介绍</a></div>
                    <div><a href="">加入我们</a></div>
                    <div><a href="">商务合作</a></div>
                </dd>
            </dl>
            <div class="line"><a href="" class="other"><img src="../../img/_temp/u114.jpg" alt=""></a></div>
            <div class="line"><a href="" class="other"><img src="../../img/_temp/u116.jpg" alt=""></a></div>
        </div>
        <p>Copyright © 2014 P2PBUY.INC.  All Rights Reserved  使用本网站即表示接受用户协议</p>
        <p>P2PBUY 版权所有 京ICP备20080101</p>
    </div>
<script src="http://res.p2pbuy.net/js/jquery-1.11.1.min.js"></script>
<script src="http://res.p2pbuy.net/js/common.js"></script>
<script src="http://res.p2pbuy.net/js/order/confirmorder.js?version=<?php echo time()?>"></script>
</body>

</html>


<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="http://res.p2pbuy.net/css/theme.css">
	<meta charset="utf-8" />
	<title>确认订单</title>
	<meta name="generator" content="BBEdit 10.5" />
</head>
<body>
 <?php include TPL_PATH."/comm/head.phtml"?>
 <div id="breadcrumb">
 <p><a href="#">我的带购</a> > <a href="#">我的订单</a> > <text id="currentpage"><a href="#">确认订单</a></text></p>
 </div>
 
 <div class="wizard">
 <ul>
    <li>买家提交订单</li>
 	<li>买手确认接单</li>
  	<a href="#"><li id="wizard_current">买家付款</li></a>
 	<li>买家购买商品</li>
 	<li>买家补齐货款</li>
 	<li>买家发货</li>
 	<li>买家确认收货</li>
 </ul>
 </div>


  
  
<p class="order_success_title">订单提交成功，请等候买手接单 <text class="item_ID">订单号：<?=$boid?></text><text class="cancel_order">取消订单</text><p/>   
<div id="order_success">
   <p class="track_order">跟踪订单</p>
  

   <table id="check_list_table">
    <tr id="table_header">
    <th>进度环节</th>
    <th>状态</th>		
    <th>操作人</th>
    
  
    </tr>
    <tr>
    <td class="current_step">提交订单</td>
    <td class="table_content">订单已经提交</td>
    <td class="table_content">买家（<?=$viewer['nick']?>）</td>
   		
 
    </tr>
    <tr>
    <td>买手接单</td>
    <td class="table_content">已提交指定买手（账单大门）等待买手接单</td>
    <td class="table_content">系统提交</td>
    
    </tr>
    <tr>
    <td>买手预付费用</td>
    <td class="table_content">未支付</td>
    <td class="table_content">％5， 预付</td>
 		

    </tr>
  
    </table>
	
  
  <p><text class="downpayment_tooltip">提前预付定金，买手会更快的接单哦</text></p>
  <p class="total_money_2">预付总额（人民币）： <text class="money_highlight">¥<?=$bidprice?></text><p>
  </br>
  <form target="_blank" method="get" action="https://shenghuo.alipay.com/send/payment/fill.htm">
  <input type="button" value="预付定金" id="payment" class="down_payment_btn" action-data="bid=<?=$bid?>&boid=<?=$boid?>&biduid=<?=$biduid?>&bidprice=<?=$bidprice?>"/>
  </form>
  <p class="paypal">使用支付宝交易，第三方资金监管保证。支付宝账号：maobaiou@aliyun.com</p>
   </form>
</div>
<script src="http://res.p2pbuy.net/js/jquery-1.11.1.min.js"></script>
<script src="http://res.p2pbuy.net/js/common.js"></script>
<script src="http://res.p2pbuy.net/js/order/confirmorder.js"></script>
</body>
</html>
-->