<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="http://182.92.129.19/css/theme.css">
	<meta charset="utf-8" />
	<title>确认订单</title>
	<meta name="generator" content="BBEdit 10.5" />
</head>
<body>
 <?php include TPL_PATH."/comm/head.phtml"?>
 <div id="breadcrumb">
 <p><a href="#">我的带购</a> > <a href="#">我的订单</a> > <text id="currentpage"><a href="#">确认订单</a></text></p>
 </div>
 
 <div class="wizard">
 <ul>
    <li>买家提交订单</li>
 	<li>买手确认接单</li>
  	<a href="#"><li id="wizard_current">买家付款</li></a>
 	<li>买家购买商品</li>
 	<li>买家补齐货款</li>
 	<li>买家发货</li>
 	<li>买家确认收货</li>
 </ul>
 </div>


  
  
<p class="order_success_title">订单提交成功，请等候买手接单 <text class="item_ID">订单号：<?=$boid?></text><text class="cancel_order">取消订单</text><p/>   
<div id="order_success">
   <p class="track_order">跟踪订单</p>
  

   <table id="check_list_table">
    <tr id="table_header">
    <th>进度环节</th>
    <th>状态</th>		
    <th>操作人</th>
    
  
    </tr>
    <tr>
    <td class="current_step">提交订单</td>
    <td class="table_content">订单已经提交</td>
    <td class="table_content">买家（<?=$viewer['nick']?>）</td>
   		
 
    </tr>
    <tr>
    <td>买手接单</td>
    <td class="table_content">已提交指定买手（账单大门）等待买手接单</td>
    <td class="table_content">系统提交</td>
    
    </tr>
    <tr>
    <td>买手预付费用</td>
    <td class="table_content">未支付</td>
    <td class="table_content">％5， 预付</td>
 		

    </tr>
  
    </table>
	
  
  <p><text class="downpayment_tooltip">提前预付定金，买手会更快的接单哦</text></p>
  <p class="total_money_2">预付总额（人民币）： <text class="money_highlight">¥<?=$bidprice?></text><p>
  </br>
  <form target="_blank" method="get" action="https://shenghuo.alipay.com/send/payment/fill.htm">
  <input type="button" value="预付定金" id="payment" class="down_payment_btn" action-data="bid=<?=$bid?>&boid=<?=$boid?>&biduid=<?=$biduid?>&bidprice=<?=$bidprice?>"/>
  </form>
  <p class="paypal">使用支付宝交易，第三方资金监管保证。支付宝账号：maobaiou@aliyun.com</p>
   </form>
</div>
<script src="/js/jquery-1.11.1.min.js"></script>
<script src="/js/common.js"></script>
<script src="/js/order/confirmorder.js"></script>
</body>
</html>
