<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
<meta charset="utf-8">
<title>我要帮人买</title>
<meta name="description" content="P2PBUY">
<link href="http://<?=$domain['res']?>/css/module/combine.css" rel="stylesheet">
<link href="http://<?=$domain['res']?>/css/page/seller-order.css" rel="stylesheet">
</head>

<body class="P-seller-order">
    <div class="header">
        <?php include TPL_PATH."/comm/header.phtml"?>

        <dl class="head-wrap clearfix">
            <dt class="logo logo-small"><a href="" title="P2PBUY">P2PBUY</a></dt>
            <dd class="search-box">
                <div class="search-wrapper"><input type="text" class="search-input" placeholder="输入订单号"><a href="" class="submit" title="搜索">搜索</a></div>
            </dd>
        </dl>
    </div>

    <div class="main-content">
        <div class="guide"><strong class="position">当前位置:</strong><span class="cur">我要帮人买</span></div>
        <div class="myorder">
            <div class="tabtype">
                <!-- <ul class="inline">
                    <li>
                        <select>
                            <option>全部订单</option>
                            <option>出价订单</option>
                            <option>已接订单</option>
                        </select>
                    </li>
                    <li><a href="">全部</a>
                    </li>
                    <li><a href="">出价订单</a>
                    </li>
                    <li><a href="">已接订单</a>
                    </li>
                </ul> -->
                

            </div>
            <div class="tabcontent">
                <div class="service-list order-all">
                    <ul class="th inline">
                        <li class="a">订单信息</li>
                        <li class="b">价格</li>
                        <li class="c">状态</li>
                        <li class="d">操作</li>
                    </ul>
                    <ul class="tbody unstyled" id="orderLists">
                    	<?php foreach($results as $result):?>
                    	<li>
                            <div class="order-num">订单号：
                                <span class="number"><?=$result['boid']?></span>
                                <span class="time"><?=$result['createtime']?></span>
                            </div>
                            <ul class="inline">
                                <li class="a clearfix">
                                    <div class="pic">
                                        <img src="<?php if($result['img']):?><?=$result['img'];?><?php else:?>/img/usa.png<?php endif;?>" alt="">
                                    </div>
                                    <div class="detail">
                                        <div class="name"><em>订单名：</em><span><?=$result['title']?></span></div>
                                        <div class="num"><em>订单描述：</em><span><?=$result['description']?></span></div>
                                        <div class="num"><em>数量：</em><span><?=$result['quantity']?></span></div>
                                        <div class="num"><em>备注：</em><span><?=$result['additional']?></span></div>
                                    </div>
                                </li>
                                <li class="b">￥<?=$result['price']?></li>
                                <li class="c">
                                    <small>
                                        <!-- <span>3个竞价</span>
                                        <a href="">查看详情</a> -->
                                        <span>竞价中</span>
                                    </small>
                                </li>
                                <li class="d">
                                    <small>
                                    	<a href="/order/takeorder?boids=<?=$result['boid']?>" class="btn btn-primary" target="_blank">我要竞价</a>
                                        <!-- <a href="" class="btn">取消</a> -->
                                    </small>
                                </li>
                            </ul>
                        </li>
                    	<?php endforeach;?>
                    </ul>
                </div>
            </div>
            <!-- <ul class="pager">
                <li><a href="#">上一页</a>
                </li>
                <li><a href="#">...</a>
                </li>
                <li><a href="#">7</a>
                </li>
                <li><a href="#">8</a>
                </li>
                <li><a href="#">9</a>
                </li>
                <li><a href="#">...</a>
                </li>
                <li><a href="#">下一页</a>
                </li>
            </ul> -->
        </div>
    </div>
    

    <?php include TPL_PATH."/comm/footer.phtml"?>
    
	<div id="scrollflag"></div>
<script src="http://<?=$domain['res']?>/js/jquery-1.11.1.min.js"></script>
<script src="http://<?=$domain['res']?>/js/common.js"></script>
<script src="http://<?=$domain['res']?>/js/order/list.js"></script>
</body>

</html>







<!-- <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="http://res.p2pbuy.net/css/theme.css">
	<meta charset="utf-8" />
	<title><?=_('代购')?></title>
	<meta name="generator" content="BBEdit 10.5" />
</head>
<body>
 <?php include TPL_PATH."/comm/head.phtml"?>
 <div id="breadcrumb">
 <p><a href="#">首页</a> > <a href="#">目的地</a> > <text id="currentpage"><a href="#">北美</a></text></p>
 </div>
 <div id="big_title_en">
 <p>North America</p>
 </div>
 <div id="sub_title_cn">
 <p>北美</p>
 </div>
 <div id="homepage_post">
 	<ul>
 	    <li><a href="javascript:void(0);" action-type="create_order" target="_blank">发布北美代购需求</a></li>
 		<li>172位买手正在旅行</br>98827位买手即将出发</li>
 	</ul>
 </div>
 <div id="country_cate">
 <p>
 <a href="#"><text class="country_selected">北美热门国家</text></a> | <a href="#">全部国家</a></br>
 看上哪个了？把链接放进去试试看<input node-type="thirdurl" style="width:300px"/></br>
 支持的网站 www.amazon.com
 </p>
 </div>
 
 <div id="orderLists">
 <?php foreach($results as $result):?>
 <div class="list_1">
 <img src="<?php if($result['img']):?><?=$result['img'];?><?php else:?>/img/usa.png<?php endif;?>" alt="item1" height="180px" width="294px"/>
 <div class="item_title">
 	<ul>
 	  <li class="first_title"><?=$result['title']?></li>
 	  <li>32位买手正好旅行</li>
 	  <li>827位买手即将出发</li>
 	  <?php if($result['thirdurl']):?>
 	  <li><a href="<?=$result['thirdurl']?>" target="_blank">点击查看商品来源</a></li>
 	  <?php endif;?>
 	  <li class="item_content">
      <?=$result['description']?><br>
      <?=$result['additional']?>
      </li></br></br></br></br></br></br></br>
      <li class="hot_destination_title">热门旅行地:</li>
      <li><a href="#">旧约</a></li>
      <li><a href="#">芝加哥</a></li>
      <li><a href="#">旧金山</a></li></br></br></br>
      <div class="buyer_trip">
      <li class="hot_destination_title">买手行程:</li>
      <li><a href="#">白夜</a></li>
      <li><a href="#">硅谷淘金之旅</a></li>
      <li><a href="#">科技产品一网打尽</a></li>
      <li><a href="#"><?=$result['person']['nick']?></a></li>
      </div></br>
      <li><a href="/order/takeorder?boids=<?=$result['boid']?>" target="_blank">我要接单</a></li>
    </ul>
 </div>
 </div>
 <?php endforeach;?>
 </div>
 <div id="scrollflag"></div>
<script src="http://res.p2pbuy.net/js/jquery-1.11.1.min.js"></script>
<script src="http://res.p2pbuy.net/js/common.js"></script>
<script src="http://res.p2pbuy.net/js/order/list.js"></script>
</body>
</html>
 -->
