<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
<meta charset="utf-8">
<title>人民海淘-我要帮人买</title>
<meta name="description" content="P2PBUY">
<link href="http://<?=$domain['res']?>/css/module/combine.css" rel="stylesheet">
<link href="http://<?=$domain['res']?>/css/page/seller-order.css" rel="stylesheet">
</head>

<body class="P-seller-order">
    <div class="header">
        <?php include TPL_PATH."/comm/header.phtml"?>

        <dl class="head-wrap clearfix">
            <dt class="logo logo-small"><a href="" title="P2PBUY">P2PBUY</a></dt>
            <dd class="search-box">
                <div class="search-wrapper"><input type="text" class="search-input" placeholder="输入订单号"><a href="" class="submit" title="搜索">搜索</a></div>
            </dd>
        </dl>
    </div>

    <div class="main-content">
        <div class="guide"><strong class="position">当前位置:</strong><span class="cur">我要帮人买</span></div>
        <div class="myorder">
            <div class="tabtype">
                <!-- <ul class="inline">
                    <li>
                        <select>
                            <option>全部订单</option>
                            <option>出价订单</option>
                            <option>已接订单</option>
                        </select>
                    </li>
                    <li><a href="">全部</a>
                    </li>
                    <li><a href="">出价订单</a>
                    </li>
                    <li><a href="">已接订单</a>
                    </li>
                </ul> -->
                

            </div>
            <div class="tabcontent">
                <div class="service-list order-all">
                    <ul class="th inline">
                        <li class="a">订单信息</li>
                        <li class="b">价格</li>
                        <li class="c">状态</li>
                        <li class="d">操作</li>
                    </ul>
                    <ul class="tbody unstyled" id="orderLists">
                    	<?php foreach($results as $result):?>
                    	<li>
                            <div class="order-num">订单号：
                                <span class="number"><?=$result['boid']?></span>
                                <span class="time"><?=$result['createtime']?></span>
                            </div>
                            <ul class="inline">
                                <li class="a clearfix">
                                    <div class="pic">
                                        <img src="<?php if($result['img']):?><?=$result['img'];?><?php else:?>/img/usa.png<?php endif;?>" alt="">
                                    </div>
                                    <div class="detail">
                                        <div class="name"><em>订单详情：</em><span><a href="/order/show?boid=<?=$result['boid']?>" target="_blank"><?=$result['boid']?></a></span></div>
                                        <div class="num"><em>商品URL：</em><span><a href="<?=$result['thirdurl']?>" target="_blank"><?=$result['thirdurl']?></a></span></div>
                                        <div class="num"><em>数量：</em><span><?=$result['quantity']?></span></div>
                                        <div class="num"><em>备注：</em><span><?=$result['additional']?></span></div>
                                    </div>
                                </li>
                                <li class="b">￥<?=$result['price']?></li>
                                <li class="c">
                                    <small>
                                        <!-- <span>3个竞价</span>
                                        <a href="">查看详情</a> -->
                                        <span>竞价中</span>
                                    </small>
                                </li>
                                <li class="d">
                                    <small>
                                    	<a href="/order/takeorder?boids=<?=$result['boid']?>" class="btn btn-primary" target="_blank">我要竞价</a>
                                        <!-- <a href="" class="btn">取消</a> -->
                                    </small>
                                </li>
                            </ul>
                        </li>
                    	<?php endforeach;?>
                    </ul>
                </div>
            </div>
            <ul class="pager" id="pager">
            向下拉，还有更多
            </ul>
            <!-- <ul class="pager">
                <li><a href="#">上一页</a>
                </li>
                <li><a href="#">...</a>
                </li>
                <li><a href="#">7</a>
                </li>
                <li><a href="#">8</a>
                </li>
                <li><a href="#">9</a>
                </li>
                <li><a href="#">...</a>
                </li>
                <li><a href="#">下一页</a>
                </li>
            </ul> -->
        </div>
    </div>
    

    <?php include TPL_PATH."/comm/footer.phtml"?>
    
	<div id="scrollflag"></div>
<script src="http://<?=$domain['res']?>/js/jquery-1.11.1.min.js"></script>
<script src="http://<?=$domain['res']?>/js/common.js"></script>
<script src="http://<?=$domain['res']?>/js/order/list.js"></script>
</body>

</html>
