<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="http://182.92.129.19/css/theme.css">
	<meta charset="utf-8" />
	<title>我的订单</title>
	<meta name="generator" content="BBEdit 10.5" />
</head>
<body>
 <?php include TPL_PATH."/comm/head.phtml"?>
 <div id="breadcrumb">
 <p><a href="#">我的带购</a> > <text id="currentpage"><a href="#">我的订单</a></text></p>
 </div>
 
 <div class="wizard">
 <ul>
    <li>买家提交订单</li>
 	<li>买手确认接单</li>
  	<a href="#"><li id="wizard_current">买家预付费用</li></a>
 	<li>买家购买商品</li>
 	<li>买家补齐货款</li>
 	<li>买家发货</li>
 	<li>买家确认收货</li>
 </ul>
 </div>


  
  
<div class="purchase_complete">
	<p id="purchase_complete_title"><?=$viewer['nick']?>的订单</p>
	<?php foreach($myBuyOrders as $myBuyOrder):?>
		<ul class="item_content_details">
		<img src="<?php if($myBuyOrder['img']):?><?=$myBuyOrder['img'];?><?php else:?>/img/usa.png<?php endif;?>" alt="item1" height="135px" width="220px" class="item_content_image"/>
			<li>订单ID：<?=$myBuyOrder['boid'];?></li>
			<li>订单名称：<?=$myBuyOrder['title'];?></li>
			<li>订单描述：<?=$myBuyOrder['description'];?></li>
			<li>商品价格：<?=$myBuyOrder['price'];?></li>
			<li>商品数量：<?=$myBuyOrder['quantity'];?></li>
			<li>补充说明：<?=$myBuyOrder['additional'];?></li>
			<li>创建时间：<?=$myBuyOrder['createtime'];?></li>
    	</ul>
    	已经存在的竞价：
		</br>
		<?php if($myBuyOrder['lock'] == 1):?>
			</br>
			订单已经付款
		<?php else:?>
			<?php if(empty($bidPrices[$myBuyOrder['boid']])):?>
				还没有出价
			<?php else:?>
				<?php foreach($bidPrices[$myBuyOrder['boid']] as $bidPrice):?>
				<form method="post" action="/order/confirmorder">
				出价：<?=$bidPrice['price']?></br>
				出价时间：<?=$bidPrice['createtime']?></br>
				出价人ID：<?=$bidPrice['uid']?></br>
				<input type="hidden" name="bid" value="<?=$bidPrice['id'];?>"/>
				<input type="hidden" name="boid" value="<?=$myBuyOrder['boid'];?>"/>
				<input type="hidden" name="bidprice" value="<?=$bidPrice['price'];?>"/>
				<input type="hidden" name="biduid" value="<?=$bidPrice['uid']?>"/>
				<input type="submit" value="确认竞价"/>
				</form>
				</br>
				</br>
				<?php endforeach;?>
			<?php endif;?>
		<?php endif;?>
    	</br>
    <?php endforeach;?>
    
</div>


  
<div class="purchase_complete">
	<p id="purchase_complete_title"><?=$viewer['nick']?>接下的订单</p>

	<?php foreach($myTakeOrders as $myTakeOrder):?>
	<ul class="item_content_details">
	<img src="<?php if($myTakeOrder['img']):?><?=$myTakeOrder['img'];?><?php else:?>/img/usa.png<?php endif;?>" alt="item1" height="135px" width="220px" class="item_content_image"/>
			<li>订单ID：<?=$myTakeOrder['boid'];?></li>
			<li>订单名称：<?=$myTakeOrder['title'];?></li>
			<li>订单描述：<?=$myTakeOrder['description'];?></li>
			<li>商品价格：<?=$myTakeOrder['price'];?></li>
			<li>商品数量：<?=$myTakeOrder['quantity'];?></li>
			<li>补充说明：<?=$myTakeOrder['additional'];?></li>
			<li>创建时间：<?=$myTakeOrder['createtime'];?></li>
    </ul>
    </br>
    <?php endforeach;?>
</div>

<div class="purchase_complete">
	<p id="purchase_complete_title"><?=$viewer['nick']?>出过价的订单</p>

	<?php foreach($myBidOrders as $myBidOrder):?>
	<ul class="item_content_details">
	<img src="<?php if($myBidOrder['img']):?><?=$myBidOrder['img'];?><?php else:?>/img/usa.png<?php endif;?>" alt="item1" height="135px" width="220px" class="item_content_image"/>
			<li>订单ID：<?=$myBidOrder['boid'];?></li>
			<li>订单名称：<?=$myBidOrder['title'];?></li>
			<li>订单描述：<?=$myBidOrder['description'];?></li>
			<li>商品价格：<?=$myBidOrder['price'];?></li>
			<li>商品数量：<?=$myBidOrder['quantity'];?></li>
			<li>补充说明：<?=$myBidOrder['additional'];?></li>
			<li>创建时间：<?=$myBidOrder['createtime'];?></li>
    </ul>
    </br>
    <?php endforeach;?>
</div>
</body>
</html>

