<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- <html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="http://182.92.129.19/css/theme.css">
	<meta charset="utf-8" />
	<title><?=_('我的订单')?></title>
	<meta name="generator" content="BBEdit 10.5" />
</head>
<body>
昵称：<?=$viewer['nick']?>
</br>
用户类型：<?php if($viewer['extends']['type'] == 2):?>买手<?php else:?>买家<?php endif;?>
</br>
</br>
</br>
我的订单
</br>
</br>
<?php foreach($myBuyOrders as $myBuyOrder):?>
订单ID：<?=$myBuyOrder['boid'];?></br>
订单名称：<?=$myBuyOrder['title'];?></br>
订单描述：<?=$myBuyOrder['description'];?></br>
商品价格：<?=$myBuyOrder['price'];?></br>
商品数量：<?=$myBuyOrder['quantity'];?></br>
补充说明：<?=$myBuyOrder['additional'];?></br>
创建时间：<?=$myBuyOrder['createtime'];?></br>
</br>
已经存在的竞价：
</br>
<?php if(empty($bidPrices[$myBuyOrder['boid']])):?>
	还没有出价
<?php else:?>
	<?php foreach($bidPrices[$myBuyOrder['boid']] as $bidPrice):?>
		<form method="post" action="/order/confirmorder">
		出价：<?=$bidPrice['price']?></br>
		出价时间：<?=$bidPrice['createtime']?></br>
		出价人ID：<?=$bidPrice['uid']?></br>
		<input type="hidden" name="bid" value="<?=$bidPrice['id'];?>"/>
		<input type="hidden" name="boid" value="<?=$myBuyOrder['boid'];?>"/>
		<input type="hidden" name="bidprice" value="<?=$bidPrice['price'];?>"/>
		<input type="hidden" name="biduid" value="<?=$bidPrice['uid']?>"/>
		<input type="submit" value="确认竞价"/>
		</form>
		</br>
		</br>
	<?php endforeach;?>
<?php endif;?>
</br>
</br>
</br>
<?php endforeach;?>
</br>
</br>
</br>
我接下的订单
</br>
</br>
<?php foreach($myTakeOrders as $myTakeOrder):?>
订单ID：<?=$myTakeOrder['boid'];?></br>
订单名称：<?=$myTakeOrder['title'];?></br>
订单描述：<?=$myTakeOrder['description'];?></br>
商品价格：<?=$myTakeOrder['price'];?></br>
商品数量：<?=$myTakeOrder['quantity'];?></br>
补充说明：<?=$myTakeOrder['additional'];?></br>
创建时间：<?=$myTakeOrder['createtime'];?></br>
</br>
</br>
</br>
<?php endforeach;?>
</br>
</br>
</br>
我出过价的订单
</br>
</br>
<?php foreach($myBidOrders as $myBidOrder):?>
订单ID：<?=$myBidOrder['boid'];?></br>
订单名称：<?=$myBidOrder['title'];?></br>
订单描述：<?=$myBidOrder['description'];?></br>
商品价格：<?=$myBidOrder['price'];?></br>
商品数量：<?=$myBidOrder['quantity'];?></br>
补充说明：<?=$myBidOrder['additional'];?></br>
创建时间：<?=$myBidOrder['createtime'];?></br>
</br>
</br>
</br>
<?php endforeach;?>
</body>
</html> -->

<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="http://182.92.129.19/css/theme.css">
	<meta charset="utf-8" />
	<title>我的订单</title>
	<meta name="generator" content="BBEdit 10.5" />
</head>
<body>
 <div id="header">
	<ul id="header_left">
		<div id="logo"><li><a href="#">带购</a></li></div>
		<li><a href="#">手机代购</a></li>
		<li><a href="#">海淘梯子</a></li>
		<li><a href="#">社区</a></li>
	</ul>
	<ul id="header_right">
		<li><a href="#">帮助中心</a></li>
		<li><a href="#">我是买手</a></li>
		<li><a href="#">我的订单</a></li>
		<li><a href="#">敏感的胖子</a></li>
	</ul>
 </div>
 <div id="breadcrumb">
 <p><a href="#">我的带购</a> > <a href="#">我的订单</a> > <text id="currentpage"><a href="#">20145658</a></text></p>
 </div>
 
 <div class="wizard">
 <ul>
    <li>买家提交订单</li>
 	<li>买手确认接单</li>
  	<a href="#"><li id="wizard_current">买家预付费用</li></a>
 	<li>买家购买商品</li>
 	<li>买家补齐货款</li>
 	<li>买家发货</li>
 	<li>买家确认收货</li>
 </ul>
 </div>


  
  
<div class="purchase_complete">
	<p id="purchase_complete_title"><?=$viewer['nick']?>的订单</p>
	<?php foreach($myBuyOrders as $myBuyOrder):?>
	<ul class="item_content_details">
	<img src="<?=$myBuyOrder['img'];?>" alt="item1" height="135px" width="220px" class="item_content_image"/>
			<li>订单ID：<?=$myBuyOrder['boid'];?></li>
			<li>订单名称：<?=$myBuyOrder['title'];?></li>
			<li>订单描述：<?=$myBuyOrder['description'];?></li>
			<li>商品价格：<?=$myBuyOrder['price'];?></li>
			<li>商品数量：<?=$myBuyOrder['quantity'];?></li>
			<li>补充说明：<?=$myBuyOrder['additional'];?></li>
			<li>创建时间：<?=$myBuyOrder['createtime'];?></li>
    </ul>
    已经存在的竞价：
	</br>
	<?php if(empty($bidPrices[$myBuyOrder['boid']])):?>
		还没有出价
	<?php else:?>
		<?php foreach($bidPrices[$myBuyOrder['boid']] as $bidPrice):?>
			<form method="post" action="/order/confirmorder">
			出价：<?=$bidPrice['price']?></br>
			出价时间：<?=$bidPrice['createtime']?></br>
			出价人ID：<?=$bidPrice['uid']?></br>
			<input type="hidden" name="bid" value="<?=$bidPrice['id'];?>"/>
			<input type="hidden" name="boid" value="<?=$myBuyOrder['boid'];?>"/>
			<input type="hidden" name="bidprice" value="<?=$bidPrice['price'];?>"/>
			<input type="hidden" name="biduid" value="<?=$bidPrice['uid']?>"/>
			<input type="submit" value="确认竞价"/>
			</form>
			</br>
			</br>
		<?php endforeach;?>
	<?php endif;?>
    </br>
    <?php endforeach;?>
    
</div>


  
<div class="purchase_complete">
	<p id="purchase_complete_title"><?=$viewer['nick']?>接下的订单</p>

	<?php foreach($myTakeOrders as $myTakeOrder):?>
	<ul class="item_content_details">
	<img src="<?=$myTakeOrder['img'];?>" alt="item1" height="135px" width="220px" class="item_content_image"/>
			<li>订单ID：<?=$myTakeOrder['boid'];?></li>
			<li>订单名称：<?=$myTakeOrder['title'];?></li>
			<li>订单描述：<?=$myTakeOrder['description'];?></li>
			<li>商品价格：<?=$myTakeOrder['price'];?></li>
			<li>商品数量：<?=$myTakeOrder['quantity'];?></li>
			<li>补充说明：<?=$myTakeOrder['additional'];?></li>
			<li>创建时间：<?=$myTakeOrder['createtime'];?></li>
    </ul>
    </br>
    <?php endforeach;?>
</div>

<div class="purchase_complete">
	<p id="purchase_complete_title"><?=$viewer['nick']?>出过价的订单</p>

	<?php foreach($myBidOrders as $myBidOrder):?>
	<ul class="item_content_details">
	<img src="<?=$myBidOrder['img'];?>" alt="item1" height="135px" width="220px" class="item_content_image"/>
			<li>订单ID：<?=$myBidOrder['boid'];?></li>
			<li>订单名称：<?=$myBidOrder['title'];?></li>
			<li>订单描述：<?=$myBidOrder['description'];?></li>
			<li>商品价格：<?=$myBidOrder['price'];?></li>
			<li>商品数量：<?=$myBidOrder['quantity'];?></li>
			<li>补充说明：<?=$myBidOrder['additional'];?></li>
			<li>创建时间：<?=$myBidOrder['createtime'];?></li>
    </ul>
    </br>
    <?php endforeach;?>
</div>
</body>
</html>

