<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
<meta charset="utf-8">
<title>买手订单</title>
<meta name="description" content="P2PBUY">
<link href="../../css/module/combine.css" rel="stylesheet">
<link href="../../css/page/seller-order.css" rel="stylesheet">
</head>

<body class="P-seller-order">
    <div class="header">
        <?php include TPL_PATH."/comm/header.phtml"?>

        <dl class="head-wrap clearfix">
            <dt class="logo logo-small"><a href="" title="P2PBUY">P2PBUY</a></dt>
            <dd class="search-box">
                <div class="search-wrapper"><input type="text" class="search-input" placeholder="输入订单号"><a href="" class="submit" title="搜索">搜索</a></div>
            </dd>
        </dl>
    </div>

    <div class="main-content">
        <div class="guide"><strong class="position">当前位置:</strong><span class="cur">我的订单</span></div>
        <!-- 某人的订单 -->
        <div class="myorder" id="myorder">
            <div class="tabtype">
                <ul class="inline"><?=$viewer['nick']?>的订单</ul>
            </div>
            <div class="tabcontent">
                <div class="service-list order-all">
                    <ul class="th inline">
                        <li class="a">订单信息</li>
                        <li class="b">价格</li>
                        <li class="c">状态</li>
                        <li class="d">操作</li>
                    </ul>
                    <ul class="tbody unstyled">
                    	<?php foreach($myBuyOrders as $myBuyOrder):?>
                    	<?php if($myBuyOrder['status'] > 0):?>
                        <li>
                            <div class="order-num">订单号：
                                <span class="number"><?=$myBuyOrder['boid']?></span>
                                <span class="time"><?=$myBuyOrder['createtime']?></span>
                            </div>
                            <ul class="inline">
                                <li class="a clearfix">
                                    <div class="pic">
                                        <img src="<?php if($myBuyOrder['img']):?><?=$myBuyOrder['img'];?><?php else:?>/img/usa.png<?php endif;?>" alt="">
                                    </div>
                                    <div class="detail">
                                        <div class="name"><em>订单名：</em><span><?=$myBuyOrder['title'];?></span></div>
                                        <div class="num"><em>订单描述：</em><span><?=$myBuyOrder['description'];?></span></div>
                                        <div class="num"><em>数量：</em><span><?=$myBuyOrder['quantity'];?></span></div>
                                        <div class="num"><em>备注：</em><span><?=$myBuyOrder['additional'];?></span></div>
                                    </div>
                                </li>
                                <li class="b"><?php if($myBuyOrder['price'] != '0.00'):?>￥<?=$myBuyOrder['price']?><?php else:?><?php echo '还没有出价';?><?php endif;?></li>
                                <li class="c">
                                    <small>
                                    	<?php if($myBuyOrder['lock'] == 1):?>
                                    	<span>订单已付款</span>
                                    	<?php endif;?>
                                    </small>
                                </li>
                                <li class="d">
                                    <small>
                                    	<?php if($myBuyOrder['lock'] != 1):?>
                                    	<a href="javascript:void(0);" class="btn" action-type="cancelorder" action-data="boid=<?=$myBuyOrder['boid']?>">取消</a>
                                    	<?php endif;?>
                                    </small>
                                </li>
                            </ul>
                        </li>
                        <?php endif;?>
                        <?php endforeach;?>
                    </ul>
                </div>
                
            </div>
        </div>
        
        <!-- 接下的订单 -->
        <div class="myorder">
            <div class="tabtype">
                <ul class="inline"><?=$viewer['nick']?>接下的订单</ul>
            </div>
            <div class="tabcontent">
                <div class="service-list order-all">
                    <ul class="th inline">
                        <li class="a">订单信息</li>
                        <li class="b">价格</li>
                        <li class="c">状态</li>
                        <li class="d">操作</li>
                    </ul>
                    <ul class="tbody unstyled">
                    	<?php foreach($myTakeOrders as $myTakeOrder):?>
                        <li>
                            <div class="order-num">订单号：
                                <span class="number"><?=$myTakeOrder['boid']?></span>
                                <span class="time"><?=$myTakeOrder['createtime']?></span>
                            </div>
                            <ul class="inline">
                                <li class="a clearfix">
                                    <div class="pic">
                                        <img src="<?php if($myTakeOrder['img']):?><?=$myTakeOrder['img'];?><?php else:?>/img/usa.png<?php endif;?>" alt="">
                                    </div>
                                    <div class="detail">
                                        <div class="name"><em>订单名：</em><span><?=$myTakeOrder['title']?></span></div>
                                        <div class="num"><em>订单描述：</em><span><?=$myTakeOrder['description']?></span></div>
                                        <div class="num"><em>数量：</em><span><?=$myTakeOrder['quantity']?></span></div>
                                        <div class="num"><em>备注：</em><span><?=$myTakeOrder['additional']?></span></div>
                                    </div>
                                </li>
                                <li class="b">￥<?=$myTakeOrder['dealprice']?></li>
                                <li class="c">
                                    <small>
                                        <span>锁定</span>
                                    </small>
                                </li>
                                <li class="d">
                                    <small>
                                    </small>
                                </li>
                            </ul>
                        </li>
                        <?php endforeach;?>
                    </ul>
                </div>
                
            </div>
        </div>
        
        <!-- 出过价的订单 -->
        <div class="myorder">
            <div class="tabtype">
                <ul class="inline"><?=$viewer['nick']?>出过价的订单</ul>
            </div>
            <div class="tabcontent">
                <div class="service-list order-all">
                    <ul class="th inline">
                        <li class="a">订单信息</li>
                        <li class="b">我出的价格</li>
                        <li class="c">状态</li>
                        <li class="d">操作</li>
                    </ul>
                    <ul class="tbody unstyled">
                    	<?php foreach($myBidOrders as $myBidOrder):?>
                        <li>
                            <div class="order-num">订单号：
                                <span class="number"><?=$myBidOrder['boid']?></span>
                                <span class="time"><?=$myBidOrder['createtime']?></span>
                            </div>
                            <ul class="inline">
                                <li class="a clearfix">
                                    <div class="pic">
                                        <img src="<?php if($myBidOrder['img']):?><?=$myBidOrder['img'];?><?php else:?>/img/usa.png<?php endif;?>" alt="">
                                    </div>
                                    <div class="detail">
                                        <div class="name"><em>订单名：</em><span><?=$myBidOrder['title']?></span></div>
                                        <div class="num"><em>订单描述：</em><span><?=$myBidOrder['description']?></span></div>
                                        <div class="num"><em>数量：</em><span><?=$myBidOrder['quantity']?></span></div>
                                        <div class="num"><em>备注：</em><span><?=$myBidOrder['additional']?></span></div>
                                    </div>
                                </li>
                                <li class="b">
                                <?php 
							    $info['boids'] = $myBidOrder['boid'];
							    $takeOrderBidPrice = Dr_Bid::getBidPriceByBoidsByApi($info);
							    ?>
							    
							    <?php foreach($takeOrderBidPrice[$myBidOrder['boid']] as $bidPriceInfo):?>
							    	<?php if($bidPriceInfo['uid'] == $viewer['uid']):?>
							    		￥<?=$bidPriceInfo['price'];?></br>
							    	<?php endif;?>
							    <?php endforeach;?>
                                </li>
                                <li class="c">
                                    <small>
                                    </small>
                                </li>
                                <li class="d">
                                    <small>
                                    </small>
                                </li>
                            </ul>
                        </li>
                        <?php endforeach;?>
                    </ul>
                </div>
                
            </div>
        </div>
        
        <!-- 所有的订单 buyer专用 -->
        <?php if($isShowAllBuyOrder):?>
        <div class="myorder" id="allorder">
            <div class="tabtype">
                <ul class="inline">所有的订单</ul>
				</br>
                <ul class="inline">输入订单号搜索订单<input type="text" action-type="searchOrder"/></ul>
            </div>
            <div class="tabcontent">
                <div class="service-list order-all">
                    <ul class="th inline">
                        <li class="a">订单信息</li>
                        <li class="b">价格</li>
                        <li class="c">状态</li>
                        <li class="d">操作</li>
                    </ul>
                    <ul class="tbody unstyled" id="allOrderInfos">
                    	<?php foreach($allBuyOrders as $allBuyOrder):?>
                        <li>
                            <div class="order-num">订单号：
                                <span class="number"><?=$allBuyOrder['boid']?></span>
                                <span class="time"><?=$allBuyOrder['createtime']?></span>
                            </div>
                            <ul class="inline">
                                <li class="a clearfix">
                                    <div class="pic">
                                        <img src="<?php if($allBuyOrder['img']):?><?=$allBuyOrder['img'];?><?php else:?>/img/usa.png<?php endif;?>" alt="">
                                    </div>
                                    <div class="detail">
                                        <div class="name"><em>订单名：</em><span><?=$allBuyOrder['title']?></span></div>
                                        <div class="num"><em>订单描述：</em><span><?=$allBuyOrder['description']?></span></div>
                                        <div class="num"><em>数量：</em><span><?=$allBuyOrder['quantity']?></span></div>
                                        <div class="num"><em>备注：</em><span><?=$allBuyOrder['additional']?></span></div>
                                    </div>
                                </li>
                                <li class="b">￥<?=$allBuyOrder['price']?></li>
                                <li class="c">
                                    <small>
                                    </small>
                                </li>
                                <li class="d">
                                    <small>
                                    	<?php if($allBuyOrder['isshow']):?>
                                    	<a href="javascript:void(0);" class="btn btn-primary" action-type="isshow" action-data="boid=<?=$allBuyOrder['boid']?>&isshow=0">关闭</a>
                                    	<?php else:?>
                                        <a href="javascript:void(0);" class="btn btn-primary" action-type="isshow" action-data="boid=<?=$allBuyOrder['boid']?>&isshow=1">开放</a>
                                        <?php endif;?>
                                        <a href="/order/takeorder?boids=<?=$allBuyOrder['boid']?>" target="_blank" class="btn">接单</a>
                                    </small>
                                </li>
                            </ul>
                        </li>
                        <?php endforeach;?>
                    </ul>
                </div>
                <a href="javascript:void(0);" action-type="getmoreallorder">查看更多订单</a>
            </div>
        </div>
        <?php endif;?>
        
    </div>

    <?php include TPL_PATH."/comm/footer.phtml"?>
<script src="http://res.p2pbuy.net/js/jquery-1.11.1.min.js"></script>
<script src="http://res.p2pbuy.net/js/common.js"></script>
<script src="http://res.p2pbuy.net/js/order/myorder.js"></script>
</body>

</html>


<!-- <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="http://res.p2pbuy.net/css/theme.css">
	<meta charset="utf-8" />
	<title>我的订单</title>
	<meta name="generator" content="BBEdit 10.5" />
</head>
<body>
 <?php include TPL_PATH."/comm/head.phtml"?>
 <div id="breadcrumb">
 <p><a href="#">我的带购</a> > <text id="currentpage"><a href="#">我的订单</a></text></p>
 </div>
 
 <div class="wizard">
 <ul>
    <li>买家提交订单</li>
 	<li>买手确认接单</li>
  	<a href="#"><li id="wizard_current">买家预付费用</li></a>
 	<li>买家购买商品</li>
 	<li>买家补齐货款</li>
 	<li>买家发货</li>
 	<li>买家确认收货</li>
 </ul>
 </div>


  
  
<div class="purchase_complete">
	<p id="purchase_complete_title"><?=$viewer['nick']?>的订单</p>
	<?php foreach($myBuyOrders as $myBuyOrder):?>
		<ul class="item_content_details">
		<img src="<?php if($myBuyOrder['img']):?><?=$myBuyOrder['img'];?><?php else:?>/img/usa.png<?php endif;?>" alt="item1" height="135px" width="220px" class="item_content_image"/>
			<li>订单ID：<?=$myBuyOrder['boid'];?></li>
			<li>订单名称：<?=$myBuyOrder['title'];?></li>
			<li>订单描述：<?=$myBuyOrder['description'];?></li>
			<li>商品价格：<?php if($myBuyOrder['price'] != '0.00'):?><?=$myBuyOrder['price']?><?php else:?><?php echo '还没有出价';?><?php endif;?></li>
			<li>商品数量：<?=$myBuyOrder['quantity'];?></li>
			<li>补充说明：<?=$myBuyOrder['additional'];?></li>
			<li>创建时间：<?=$myBuyOrder['createtime'];?></li>
    	</ul>
    	已经存在的竞价：
		</br>
		<?php if($myBuyOrder['lock'] == 1):?>
			</br>
			订单已经付款
		<?php else:?>
			<?php if(empty($bidPrices[$myBuyOrder['boid']])):?>
				还没有出价
			<?php else:?>
				<?php foreach($bidPrices[$myBuyOrder['boid']] as $bidPrice):?>
				<form method="post" action="/order/confirmorder">
				出价：<?=$bidPrice['price']?></br>
				出价时间：<?=$bidPrice['createtime']?></br>
				出价人ID：<?=$bidPrice['uid']?></br>
				<input type="hidden" name="bid" value="<?=$bidPrice['id'];?>"/>
				<input type="hidden" name="boid" value="<?=$myBuyOrder['boid'];?>"/>
				<input type="hidden" name="bidprice" value="<?=$bidPrice['price'];?>"/>
				<input type="hidden" name="biduid" value="<?=$bidPrice['uid']?>"/>
				<input type="submit" value="确认竞价"/>
				</form>
				</br>
				</br>
				<?php endforeach;?>
			<?php endif;?>
		<?php endif;?>
    	</br>
    <?php endforeach;?>
    
</div>


  
<div class="purchase_complete">
	<p id="purchase_complete_title"><?=$viewer['nick']?>接下的订单</p>

	<?php foreach($myTakeOrders as $myTakeOrder):?>
	<ul class="item_content_details">
	<img src="<?php if($myTakeOrder['img']):?><?=$myTakeOrder['img'];?><?php else:?>/img/usa.png<?php endif;?>" alt="item1" height="135px" width="220px" class="item_content_image"/>
			<li>订单ID：<?=$myTakeOrder['boid'];?></li>
			<li>订单名称：<?=$myTakeOrder['title'];?></li>
			<li>订单描述：<?=$myTakeOrder['description'];?></li>
			<li>商品价格：<?=$myTakeOrder['price'];?></li>
			<li>商品数量：<?=$myTakeOrder['quantity'];?></li>
			<li>补充说明：<?=$myTakeOrder['additional'];?></li>
			<li>创建时间：<?=$myTakeOrder['createtime'];?></li>
    </ul>
    </br>
    <?php endforeach;?>
</div>

<div class="purchase_complete">
	<p id="purchase_complete_title"><?=$viewer['nick']?>出过价的订单</p>

	<?php foreach($myBidOrders as $myBidOrder):?>
	<ul class="item_content_details">
	<img src="<?php if($myBidOrder['img']):?><?=$myBidOrder['img'];?><?php else:?>/img/usa.png<?php endif;?>" alt="item1" height="135px" width="220px" class="item_content_image"/>
			<li>订单ID：<?=$myBidOrder['boid'];?></li>
			<li>订单名称：<?=$myBidOrder['title'];?></li>
			<li>订单描述：<?=$myBidOrder['description'];?></li>
			<li>商品价格：<?=$myBidOrder['price'];?></li>
			<li>商品数量：<?=$myBidOrder['quantity'];?></li>
			<li>补充说明：<?=$myBidOrder['additional'];?></li>
			<li>创建时间：<?=$myBidOrder['createtime'];?></li>
			<?php 
		    $info['boids'] = $myBidOrder['boid'];
		    $takeOrderBidPrice = Dr_Bid::getBidPriceByBoidsByApi($info);
		    ?>
		    
		    <?php foreach($takeOrderBidPrice[$myBidOrder['boid']] as $bidPriceInfo):?>
		    	<?php if($bidPriceInfo['uid'] == $viewer['uid']):?>
		    		<li>我出的价格：<?=$bidPriceInfo['price'];?></li>
		    	<?php endif;?>
		    <?php endforeach;?>
    </ul>
    </br>
    <?php endforeach;?>
</div>

<?php if($isShowAllBuyOrder):?>
<div class="purchase_complete" id="allorder">
	<p id="purchase_complete_title">所有的订单
	</br>
	</br>
	输入订单号搜索订单<input type="text" action-type="searchOrder"></p>

	<div id="allOrderInfos">
	<?php foreach($allBuyOrders as $allBuyOrder):?>
	<ul class="item_content_details" id="allOrderInfo">
	<img src="<?php if($allBuyOrder['img']):?><?=$allBuyOrder['img'];?><?php else:?>/img/usa.png<?php endif;?>" alt="item1" height="135px" width="220px" class="item_content_image"/>
			<li>我也买不了，展示给别人吧<input type="checkbox" action-type="isshow" <?php if($allBuyOrder['isshow']):?>checked="checked"<?php endif;?>></li>
			<li action-data="boid=<?=$allBuyOrder['boid'];?>">订单ID：<?=$allBuyOrder['boid'];?></li>
			<li>订单名称：<?=$allBuyOrder['title'];?></li>
			<li>订单描述：<?=$allBuyOrder['description'];?></li>
			<li>商品价格：<?=$allBuyOrder['price'];?></li>
			<li>商品数量：<?=$allBuyOrder['quantity'];?></li>
			<li>补充说明：<?=$allBuyOrder['additional'];?></li>
			<li>创建时间：<?=$allBuyOrder['createtime'];?></li>
    </ul>
    </br>
    <?php endforeach;?>
    </div>
</div>
<?php endif;?>
<script src="http://res.p2pbuy.net/js/jquery-1.11.1.min.js"></script>
<script src="http://res.p2pbuy.net/js/common.js"></script>
<script src="http://res.p2pbuy.net/js/order/myorder.js?version=<?php echo time()?>"></script>
</body>
</html>
 -->
