<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>支付费用</title>
<meta name="description" content="P2PBUY">
<link href="http://res.p2pbuy.net/css/module/combine.css" rel="stylesheet">
<link href="http://res.p2pbuy.net/css/page/order-pay.css" rel="stylesheet">
</head>

<body class="P-order-pay">

    <div class="header">
        <div class="top-bar">
            <div class="inner">
                <div class="login-info">
                    <!--未登录状态-->
                    <ul class="inline unlogin" style="display:none">
                        <li><a href="#">登录</a></li>
                        <li><a href="">注册</a></li>
                    </ul>
                    <!--/未登录状态-->
                    <!--已登录状态-->
                    <ul class="inline logined" style="display:">
                        <li class="message"><a href="" title="我是买手"><span>我是买手</span></a></li>
                        <li class="user"><a href="" ><span class="">香稻老农</span></a></li>
                        <li class="opt"><a href="" ><span class="">退出</span></a></li>
                    </ul>      
                    <!--/已登录状态-->
                </div>
            </div>
        </div>

        <dl class="head-wrap clearfix">
            <dt class="logo logo-small"><a href="" title="P2PBUY">P2PBUY</a></dt>
            <dd class="search-box">
                <div><input type="text" class="search-input" placeholder="直接粘贴海外商品网址"><a href="" class="btn btn-primary" title="一键海淘">一键海淘</a></div>
                <a href="" class="nolink">找不到链接？传张图片也能买！</a>
            </dd>
        </dl>
    </div>

    <div class="main-content">
        <!--购买进度-->
        <div class="step-trilogy">
            <div class="inner">
                <a href="#" class="step"><span>1.提交商品网址</span></a>
                <a href="#" class="step"><span>2.确认订单</span></a>
                <a href="#" class="step cur"><span>3.支付费用</span></a>
                <a href="#" class="step"><span>4.交易完成</span></a>
            </div>
        </div>
        <!--/购买进度-->
        <div class="order-info">
            <div class="item pay-type">
                <div class="alert">
                    <p class="S-txt5 W-fb">运费和关税均为估值，需要收到商品后按照实际重量计算，我们会在收到商品后第一时间通知您支付运费及关税，以便货物能够尽快送达。</p>
                </div>
                <div class="pay-amount"><span class="tit">您目前需要支付的费用为：订单商品价格</span><span class="W-f18 S-txt5 W-fb">￥<?=$curBuyOrderInfo['dealprice']?></span></div>
                <div class="btn-box">
                    <a href="" class="btn btn-primary">使用支付宝支付</a>
                    <a href="" class="btn btn-primary">使用微信支付</a>
                </div>
            </div>
            <div class="item goods-price">
                <h3 class="title">订单详情</h3>
                <div class="info-form">
                    <div class="head-info">
                        <ul class="thead inline clearfix">
                            <li class="th th-name"><i class="shop-amazon"></i><span class="shop-name">亚马逊美国</span></li>
                            <li class="th th-price">价格（元）</li>
                            <li class="th th-amount">数量</li>
                            <li class="th th-offer">优惠（元）</li>
                            <li class="th th-total">小计（元）</li>
                        </ul>
                    </div>
                    <div class="content-info">
                        <div class="goods-table">
                            <ul class="item-main inline clearfix">
                                <li class="td td-chk"><input class="" id="112323" type="checkbox" name="items" value=""></li>
                                <li class="td td-pic"><a href=""><img src="<?=$curBuyOrderInfo['img']?>" alt=""></a></li>
                                <li class="td td-intro">
                                    <p class="name"><?=$curBuyOrderInfo['title']?></p>
                                    <!-- <div class="size"><em>型号</em> <span>“Small ,Bonsai Green”</span></div> -->
                                </li>
                                <li class="td td-price">
                                    <div class="num"><?=$curBuyOrderInfo['dealprice']?></div>
                                </li>
                                <li class="td td-amount">
                                    <div class="num"><?=$curBuyOrderInfo['quantity']?></div>
                                </li>
                                <li class="td td-offer">
                                    <div lass="num">无优惠</div>
                                </li>
                                <li class="td td-total">
                                    <div class="num"><?=$curBuyOrderInfo['dealprice']?></div>
                                </li>
                            </ul>
                            <!-- <ul class="item-sub inline clearfix">
                                <li class="td td-chk">---</li>
                                <li class="td td-pic">---</li>
                                <li class="td td-intro">
                                   <div class="">优惠码：B00KC2SJHC</div>
                                </li>
                                <li class="td td-price">
                                    <div class="num">---</div>
                                </li>
                                <li class="td td-amount">
                                    <div class="num">1</div>
                                </li>
                                <li class="td td-offer">
                                    <div lass="num">省：300</div>
                                </li>
                                <li class="td td-total">
                                    <div class="num">-300</div>
                                </li>
                            </ul>
                            <ul class="item-sub inline clearfix">
                                <li class="td td-chk">---</li>
                                <li class="td td-pic">---</li>
                                <li class="td td-intro">
                                   <div class="">服务费</div>
                                </li>
                                <li class="td td-price">
                                    <div class="num">179.4</div>
                                </li>
                                <li class="td td-amount">
                                    <div class="num">1</div>
                                </li>
                                <li class="td td-offer">
                                    <div lass="num">满100减10元，省10元</div>
                                </li>
                                <li class="td td-total">
                                    <div class="num">-169.4</div>
                                </li>
                            </ul>
                             -->
                        </div>
                        <div class="goods-total clearfix">
                            <div class="W-fl S-txt2"><em class="tit">补充说明</em><span class="cont"><?=$curBuyOrderInfo['description']?></span></div>
                            <div class="W-fr">
                                <em class="S-txt2">合计（不含运费及关税）：</em><span class="total-price S-txt5">￥<?=$curBuyOrderInfo['dealprice']?></span>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="item goods-cost" style="display:none">
                <h3 class="title">运费及关税信息</h3>
                <div class="info-form">
                    <div class="head-info">
                        <ul class="thead inline clearfix">
                            <li class="th th-name">花费</li>
                            <li class="th th-weight">重量（磅）</li>
                            <li class="th th-type">类型</li>
                            <li class="th th-price">价格（元）</li>
                            <li class="th th-offer">优惠（元）</li>
                            <li class="th th-total">小计（元）</li>
                        </ul>
                    </div>
                    <div class="content-info">
                        <div class="cost-table">
                            <ul class="item-main inline clearfix">
                                <li class="td td-name">商品运费</li>
                                <li class="td td-weight">1.4</li>
                                <li class="td td-type">鞋服，首磅30，续重30</li>
                                <li class="td td-price">60.00</li>
                                <li class="td td-offer">B2BBUY7折，省18</li>
                                <li class="td td-total">42.00</li>
                            </ul>
                            <ul class="item-sub inline clearfix">
                                <li class="td td-name">关税</li>
                                <li class="td td-weight">---</li>
                                <li class="td td-type">奢侈品，关税比例200%</li>
                                <li class="td td-price">3588.00</li>
                                <li class="td td-offer"><em class="W-fb S-txt5">关税补贴，省3588.00</em></li>
                                <li class="td td-total">00.00</li>
                            </ul>
                        </div>
                        <div class="cost-total clearfix">
                            <div class="W-fl S-txt2"></div>
                            <div class="W-fr">
                                <em class="W-fb S-txt5">运费和关税均为估值，需要收到商品后按照实际重量计算</em><span class="total-price S-txt2">￥1663.40</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>

    <div class="footer">
        <div class="link-about clearfix">
            <div class="line">
                <div class="logo logo-small"><a href="#" title="P2PBUY">P2PBUY</a></div>
            </div>
            <dl class="line">
                <dt class="tit">新手指南</dt>
                <dd class="list">
                    <div><a href="">购买流程</a></div>
                    <div><a href="">支付方式</a></div>
                    <div><a href="">配送方式</a></div>
                </dd>
            </dl>
            <dl class="line">
                <dt class="tit">购物保障</dt>
                <dd class="list">
                    <div><a href="">正品保证</a></div>
                    <div><a href="">海外直购</a></div>
                    <div><a href="">物流说明</a></div>
                </dd>
                <dd class="list second">
                    <div><a href="">通关关税</a></div>
                    <div><a href="">常见问题</a></div>
                    <div><a href="">联系客服</a></div>
                </dd>
            </dl>
            <dl class="line">
                <dt class="tit">关于我们</dt>
                <dd class="list">
                    <div><a href="">网站介绍</a></div>
                    <div><a href="">加入我们</a></div>
                    <div><a href="">商务合作</a></div>
                </dd>
            </dl>
            <div class="line"><a href="" class="other"><img src="http://www.p2pbuy.net/img/_temp/u114.jpg" alt=""></a></div>
            <div class="line"><a href="" class="other"><img src="http://www.p2pbuy.net/img/_temp/u116.jpg" alt=""></a></div>
        </div>
        <p>Copyright © 2014 P2PBUY.INC.  All Rights Reserved  使用本网站即表示接受用户协议</p>
        <p>P2PBUY 版权所有 京ICP备20080101</p>
    </div>
    
</body>

</html>
