<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="http://182.92.129.19/css/theme.css">
	<meta charset="utf-8" />
	<title><?=_('我要接单')?></title>
	<meta name="generator" content="BBEdit 10.5" />
</head>
<body id="bidbuyorder_form">
 <div id="header">
	<ul id="header_left">
		<div id="logo"><li><a href="#">带购</a></li></div>
		<li><a href="#">手机代购</a></li>
		<li><a href="#">海淘梯子</a></li>
		<li><a href="#">社区</a></li>
	</ul>
	<ul id="header_right">
		<li><a href="#">帮助中心</a></li>
		<li><a href="#">我是买手</a></li>
		<li><a href="#">我的订单</a></li>
		<li><a href="#">敏感的胖子</a></li>
	</ul>
 </div>
 <div id="breadcrumb">
 <p><a href="#">我的带购</a> > <a href="#">我的订单</a> > <text id="currentpage"><a href="#">20145658</a></text></p>
 </div>
 
 <div class="wizard">
 <ul>
    <li>买家提交订单</li>
 	<li>买手确认接单</li>
  	<a href="#"><li id="wizard_current">买家预付费用</li></a>
 	<li>买家购买商品</li>
 	<li>买家补齐货款</li>
 	<li>买家发货</li>
 	<li>买家确认收货</li>
 </ul>
 </div>

<div class="purchase_complete">
<form onsubmit="return false;">
<ul class="item_content">
	<li>
		<img src="<?=$buyOrder['img']?>" alt="item1" height="135px" width="220px" class="item_content_image">
		<ul class="item_content_details">
			<li>订单名称：<?=$buyOrder['title'];?></li>
			<li>订单描述：<?=$buyOrder['description'];?></li>
			<li>商品价格：<?=$buyOrder['price'];?>(人民币)</li>
			<li>商品数量：<?=$buyOrder['quantity'];?></li>
			<li>补充说明：<?=$buyOrder['additional'];?></li>
			<li>创建时间：<?=$buyOrder['createtime'];?></li>
			<li>竞价价格：<input type="text" node-type="bidprice"/></li>
		</ul>
	</li>
</ul>
<input type="hidden" node-type="boid" value="<?=$buyOrder['boid']?>"/>
<input type="button" action-type="bidBuyOrder" value="我要竞价" name="submit" class="down_payment_btn"/>
</form>
</div>

<script src="/js/jquery-1.11.1.min.js"></script>
<script src="/js/common.js"></script>
<script src="/js/order/takeorder.js"></script>
</body>
</html>
