<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
<meta charset="utf-8">
<title>订单竞价</title>
<meta name="description" content="P2PBUY">
<link href="http://<?=$domain['res']?>/css/module/combine.css" rel="stylesheet">
<link href="http://<?=$domain['res']?>/css/page/bid-order.css" rel="stylesheet">
</head>

<body class="P-bid-order">
    <div class="header">
        <?php include TPL_PATH."/comm/header.phtml"?>

        <dl class="head-wrap clearfix">
            <dt class="logo logo-small"><a href="" title="P2PBUY">P2PBUY</a></dt>
            <dd class="search-box">
                <div class="search-wrapper"><input type="text" class="search-input" placeholder="输入订单号"><a href="" class="submit" title="搜索">搜索</a></div>
            </dd>
        </dl>
    </div>

    <div class="main-content">
        <div class="guide"><strong class="position">当前位置:</strong><span class="cur">竞价</span></div>
        <div class="myorder" id="bidbuyorder">
            <div class="tabtype">
                <ul class="inline">
                </ul>
            </div>
            <div class="tabcontent">
                <div class="service-list order-bid"">
                    <ul class="th inline">
                        <li class="a">订单信息</li>
                        <li class="b">价格</li>
                        <li class="c">状态</li>
                        <li class="d">操作</li>
                    </ul>
                    <ul class="tbody unstyled">
                        <li>
                            <div class="order-num">订单号：
                                <span class="number"><?=$buyOrder['boid']?></span>
                                <span class="time"><?=$buyOrder['createtime']?></span>
                            </div>
                            <ul class="inline">
                                <li class="a clearfix">
                                    <div class="pic">
                                        <img src="<?php if($buyOrder['img']):?><?=$buyOrder['img']?><?php else:?>/img/usa.png<?php endif;?>" alt="">
                                    </div>
                                    <div class="detail">
                                        <div class="name"><em>订单名：</em><span><?=$buyOrder['title']?></span></div>
                                        <div class="num"><em>订单描述：</em><span><?=$buyOrder['description']?></span></div>
                                        <div class="num"><em>数量：</em><span><?=$buyOrder['quantity']?></span></div>
                                        <div class="num"><em>备注：</em><span><?=$buyOrder['additional']?></span></div>
                                    </div>
                                </li>
                                <li class="b">￥<?=$buyOrder['price']?></li>
                                <li class="c">
                                    <input type="text" class="input-small" placeholder="输入您的竞价"  node-type="bidprice">
                                </li>
                                <li class="d">
                                    <small>
                                        <a href="javascript:void(0);" class="btn btn-primary" action-type="bidBuyOrder" action-data="boid=<?=$buyOrder['boid']?>">竞价</a>
                                    </small>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <?php include TPL_PATH."/comm/footer.phtml"?>
<script src="http://res.p2pbuy.net/js/jquery-1.11.1.min.js"></script>
<script src="http://res.p2pbuy.net/js/common.js"></script>
<script src="http://res.p2pbuy.net/js/order/takeorder.js"></script>   
</body>

</html>




<!-- <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="http://res.p2pbuy.net/css/theme.css">
	<meta charset="utf-8" />
	<title><?=_('我要接单')?></title>
	<meta name="generator" content="BBEdit 10.5" />
</head>
<body id="bidbuyorder_form">
 <?php include TPL_PATH."/comm/head.phtml"?>
 <div id="breadcrumb">
 <p><a href="#">我的带购</a> > <a href="#">我要接单</a> > <text id="currentpage"><a href="#"><?=$buyOrder['boid'];?></a></text></p>
 </div>
 
 <div class="wizard">
 <ul>
    <li>买家提交订单</li>
 	<li>买手确认接单</li>
  	<a href="#"><li id="wizard_current">买家预付费用</li></a>
 	<li>买家购买商品</li>
 	<li>买家补齐货款</li>
 	<li>买家发货</li>
 	<li>买家确认收货</li>
 </ul>
 </div>

<div class="purchase_complete">
<form onsubmit="return false;">
<ul class="item_content">
	<li>
		<img src="<?php if($buyOrder['img']):?><?=$buyOrder['img']?><?php else:?>/img/usa.png<?php endif;?>" alt="item1" height="135px" width="220px" class="item_content_image">
		<ul class="item_content_details">
			<li>订单名称：<?=$buyOrder['title'];?></li>
			<li>订单描述：<?=$buyOrder['description'];?></li>
			<li>商品价格：<?=$buyOrder['price'];?>(人民币)</li>
			<li>商品数量：<?=$buyOrder['quantity'];?></li>
			<li>补充说明：<?=$buyOrder['additional'];?></li>
			<li>创建时间：<?=$buyOrder['createtime'];?></li>
			<li>竞价价格：<input type="text" node-type="bidprice"/></li>
		</ul>
	</li>
</ul>
<input type="hidden" node-type="boid" value="<?=$buyOrder['boid']?>"/>
<input type="button" action-type="bidBuyOrder" value="我要竞价" name="submit" class="down_payment_btn"/>
</form>
</div>

<script src="http://res.p2pbuy.net/js/jquery-1.11.1.min.js"></script>
<script src="http://res.p2pbuy.net/js/common.js"></script>
<script src="http://res.p2pbuy.net/js/order/takeorder.js"></script>
</body>
</html> -->
