<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="http://182.92.129.19/css/theme.css">
	<meta charset="utf-8" />
	<title><?=_('我要接单')?></title>
	<meta name="generator" content="BBEdit 10.5" />
</head>
<body id="bidbuyorder_form">

<form onsubmit="return false;">
订单名称：<?=$buyOrder['title'];?></br>
订单描述：<?=$buyOrder['description'];?></br>
商品价格：<?=$buyOrder['price'];?>(人民币)</br>
商品数量：<?=$buyOrder['quantity'];?></br>
补充说明：<?=$buyOrder['additional'];?></br>
创建时间：<?=$buyOrder['createtime'];?></br>
竞价价格：<input type="text" node-type="bidprice"/></br>
<input type="hidden" node-type="boid" value="<?=$buyOrder['boid']?>"/>
<input type="button" action-type="bidBuyOrder" value="我要竞价">
</form>
<script src="/js/jquery-1.11.1.min.js"></script>
<script src="/js/common.js"></script>
<script src="/js/order/takeorder.js"></script>
</body>
</html>
