						<?php foreach($results as $result):?>
                    	<li>
                            <div class="order-num">订单号：
                                <span class="number"><?=$result['boid']?></span>
                                <span class="time"><?=$result['createtime']?></span>
                            </div>
                            <ul class="inline">
                                <li class="a clearfix">
                                    <div class="pic">
                                        <img src="<?php if($result['img']):?><?=$result['img'];?><?php else:?>/img/usa.png<?php endif;?>" alt="">
                                    </div>
                                    <div class="detail">
                                        <div class="name"><em>订单详情：</em><span><a href="/order/show?boid=<?=$result['boid']?>" target="_blank"><?=$result['boid']?></a></span></div>
                                        <div class="num"><em>商品URL：</em><span><a href="<?=$result['thirdurl']?>" target="_blank"><?=$result['thirdurl']?></a></span></div>
                                        <div class="num"><em>数量：</em><span><?=$result['quantity']?></span></div>
                                        <div class="num"><em>备注：</em><span><?=$result['additional']?></span></div>
                                    </div>
                                </li>
                                <li class="b">￥<?=$result['price']?></li>
                                <li class="c">
                                    <small>
                                        <!-- <span>3个竞价</span>
                                        <a href="">查看详情</a> -->
                                        <span>竞价中</span>
                                    </small>
                                </li>
                                <li class="d">
                                    <small>
                                        <a href="/order/takeorder?boids=<?=$result['boid']?>" class="btn btn-primary" target="_blank">我要竞价</a>
                                        <!-- <a href="" class="btn">取消</a> -->
                                    </small>
                                </li>
                            </ul>
                        </li>
                    	<?php endforeach;?>