<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?=_('带购')?></title>
</head>
<body>
<?php foreach($orderBuyInfos as $orderBuyInfo):?>
<form method="post" action="/aj/order/takeorder">
订单编号：<?=$orderBuyInfo['boid']?></br>
订单标题：<?=$orderBuyInfo['title']?></br>
商品描述：<?=$orderBuyInfo['description']?></br>
商品价格：<?=$orderBuyInfo['price']?></br>
购买数量：<?=$orderBuyInfo['quantity']?></br>
补充说明：<?=$orderBuyInfo['additional']?></br>
<input type="hidden" name="boid" value="<?=$orderBuyInfo['boid']?>" />
<input type="submit" value="我要接单" />
</form>
</br>
</br>
<?php endforeach;?>
</body>

</html>