<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
<link rel="stylesheet" type="text/css" href="http://<?=$domain['res']?>/css/module/combine.css">
<link rel="stylesheet" type="text/css" href="http://<?=$domain['res']?>/css/page/home.css">
<meta charset="utf-8" />
<title>人民海淘</title>
<meta name="description" content="海淘帮手">
<script src="http://<?=$domain['res']?>/js/jquery-1.11.1.min.js"></script>
<script src="http://<?=$domain['res']?>/js/common.js"></script>
<script src="http://<?=$domain['res']?>/js/index.js"></script>
</head>
<body class="P-home">
    <div class="header">
    	<div class="mask"></div>
    	<div class="cover">
        <!--顶部-->
            <div class="top-bar">
                <div class="inner">
                    <div class="login-info">
                    	<?php if($viewer['uid']):?>
                        <!--已登录状态-->
                        <ul class="inline logined">
                            <!-- <li class="message"><a href="" title="我的消息"><i class="icon-envelope icon-white"><em>&#8226;</em></i><span>消息</span></a></li> -->
                            <li class="message"><a href="/order/list" title="我要帮人买"><span>我要帮人买</span></a></li>
                            <li class="message"><a href="/order/myorder" title="我的订单"><span>我的订单</span></a></li>
                            <li class="head-pic"><a href="javascript:void(0);" class="img"><i class="icon-user icon-white"></i><span class="name"><?=$viewer['nick']?></span></a></li>
                        	<li class="message"><a href="/login/logout" title="退出登录"><span>退出登录</span></a></li>
                        </ul>      
                        <!--已登录状态-->
                        <?php else:?>
                        <!--未登录状态-->
                        <ul class="inline unlogin clearfix" style="display:block">
                            <li><a href="/login/login">登录</a></li>
                            <li><a href="javascript:void(0);">注册</a></li>
                            <li><a href="/order/myorder" class="cur">我是买手</a></li>
                        </ul>
                        <!--未登录状态-->
                        <?php endif;?>
                    </div>
                </div>
            </div>
            <!--/顶部-->

        <!--logo-->
        <h1 class="logo"><a href="javascript:void(0);" title="P2PBUY">P2PBUY</a></h1>
        <!--/logo-->

		<div class="slogan">
            <div class="title">最懂你的海外买手</div>
            <div class="subtitle">中国最大的专业海外买手平台</div>
        </div>

        <!--搜索-->
        <div class="search-box" id="search_tool">
        	<div class="search-wrapper"><input type="text" class="search-input" placeholder="您可以直接粘贴海外商品网址或者直接下单" node-type="thirdurl"><!-- <a href="javascript:void(0);" class="nolink"><input type="file" class="file"></a> --><a href="javascript:void(0);" class="submit" title="搜索" action-type="create_order">搜索</a></div>
        </div>
        <!--/搜索-->
        <!-- 商品展示 -->
        <div class="commodity-show">
            <ul class="inline commodity-list">
                <li><a href="/order/buy?thirdurl=<?=urlencode('http://www.amazon.com/Transcend-JetDrive-Expansion-13-Inch-TS128GJDL330/dp/B00MTHLURE/ref=sr_1_1?ie=UTF8&qid=1415782525&sr=8-1&keywords=jetdrive+lite+330')?>" title="商品标题"><img src="http://ecx.images-amazon.com/images/I/51KS7PCiWKL._SL1000_.jpg" alt="商品标题"></a></li>
                <li><a href="/order/buy?thirdurl=<?=urlencode('http://www.amazon.com/90-day-Service-Frustration-Packaging-Mobi-16-FF/dp/B00CS4WPHC/ref=sr_1_5?ie=UTF8&qid=1415782635&sr=8-5&keywords=eye-fi')?>" title="商品标题"><img src="http://ecx.images-amazon.com/images/I/51k5IwT1o8L.jpg" alt="商品标题"></a></li>
                <li><a href="/order/buy?thirdurl=<?=urlencode('http://www.amazon.com/Hubsan-SpyHawk-Controller-recording-auto-pilot/dp/B00AAICPG4/ref=sr_1_3?ie=UTF8&qid=1415782698&sr=8-3&keywords=plane+rc+camera')?>" title="商品标题"><img src="http://ecx.images-amazon.com/images/I/61C3ZaNPpDL._SL1000_.jpg" alt="商品标题"></a></li>
                <li><a href="/order/buy?thirdurl=<?=urlencode('http://store.apple.com/us/product/H9988ZM/A/michael-michael-kors-15-jet-set-travel-tote-for-macbook-pro?fnode=f42bd31f49860dd1e3fcea6989f1b4a65556836f1c3641a9e4b9e7fcd2c65ccefa2596fb2d3e06fd696a2be153d78f318e5d8954e0b416c927af0123ac3fecec53227e8f098f63ac3071b82e92bf6677009b6269b7196a913a5fb80d90a37cfe3dd5e7cfd3655f38809e22b5abb84229')?>" title="商品标题"><img src="http://store.storeimages.cdn-apple.com/4185/as-images.apple.com/is/image/AppleInc/aos/published/images/H/99/H9988/H9988?wid=800&hei=800&fmt=jpeg&qlt=95&op_sharpen=0&resMode=bicub&op_usm=0.5,0.5,0,0&iccEmbed=0&layer=comp&.v=1400794277486" alt="商品标题"></a></li>
                <li><a href="/order/buy?thirdurl=<?=urlencode('http://store.apple.com/us/product/ME177LL/A/airport-time-capsule-2tb?fnode=df33a3769ca3397f6d44ba70469121b0559163f82c14920ffc59f39513d2d9401fefb50469026b1b7232436bf9c8af5a5d7f357c6f144a1b44a45b0d6322409a3174e5cf9a057f8311c91525895406bcf173c3d893b7e28d110487b5e5c23a84edbe088289e1ca59bdd67a48c9dd2f64')?>" title="商品标题"><img src="http://store.storeimages.cdn-apple.com/4185/as-images.apple.com/is/image/AppleInc/aos/published/images/M/E1/ME177/ME177?wid=800&hei=800&fmt=jpeg&qlt=80&op_sharpen=0&resMode=bicub&op_usm=0.5,0.5,0,0&iccEmbed=0&layer=comp&.v=1400974235303" alt="商品标题"></a></li>
                <li><a href="/order/buy?thirdurl=<?=urlencode('http://store.apple.com/us/product/HFV22VC/A/philips-hue-tap-switch?fnode=e0bee6f08dd5c6cc27043cef17a8d6e85e720caece3a18e6a5480ecc99365eab0b2d51d0b91579a6406c365885307c60107b1587bb742044ad4baedf1663609d6ea863b83bfcaa00c87e8638a72b34949693c26c09270ac04a20f72bee4abe8dd3a3eaa2574068a167b9b285fad004f8')?>" title="商品标题"><img src="http://store.storeimages.cdn-apple.com/4185/as-images.apple.com/is/image/AppleInc/aos/published/images/H/FV/HFV22/HFV22?wid=800&hei=800&fmt=jpeg&qlt=95&op_sharpen=0&resMode=bicub&op_usm=0.5,0.5,0,0&iccEmbed=0&layer=comp&.v=1403780850548" alt="商品标题"></a></li>
            </ul>
        </div>
        <!-- 商品展示 -->
		</div>
    </div>

    <div class="main-content">

        <div class="goods-show">
            <h3 class="title"><span>发现喜爱的商品</span><em>跟随旅行者一起逛遍全球</em></h3>
            <div class="content">
                <ul class="inline list-media clearfix">
                    <li class="item">
                        <div class="pic"><a href="javascript:void(0);"><img data-src="" alt="图片" src="http://<?=$domain['res']?>/img/_temp/u44.jpg" width="500" height="334"></a></div>
                        <div class="caption"><a href="#">巴黎折扣村</a></div>
                    </li>
                    <li class="item">
                        <div class="pic"><a href="javascript:void(0);"><img data-src="" alt="图片" src="http://<?=$domain['res']?>/img/_temp/u54.jpg" width="500" height="334"></a></div>
                        <div class="caption"><a href="#">迪拜土豪之都</a></div>
                    </li>
                    <li class="item">
                        <div class="pic"><a href="javascript:void(0);"><img data-src="" alt="图片" src="http://<?=$domain['res']?>/img/_temp/u64.png" width="500" height="334"></a></div>
                        <div class="caption"><a href="#">美国西海岸购物天堂</a></div>
                    </li>
                    <li class="item">
                        <div class="pic"><a href="javascript:void(0);"><img data-src="" alt="图片" src="http://<?=$domain['res']?>/img/_temp/u72.png" width="500" height="334"></a></div>
                        <div class="caption"><a href="#">足不出户购尽天下商品</a></div>
                    </li>
                    <li class="item">
                        <div class="pic"><a href="javascript:void(0);"><img data-src="" alt="图片" src="http://<?=$domain['res']?>/img/_temp/u54.jpg" width="500" height="334"></a></div>
                        <div class="caption"><a href="#">迪拜土豪之都</a></div>
                    </li>
                    <li class="item">
                        <div class="pic"><a href="javascript:void(0);"><img data-src="" alt="图片" src="http://<?=$domain['res']?>/img/_temp/u44.jpg" width="500" height="334"></a></div>
                        <div class="caption"><a href="#">巴黎折扣村</a></div>
                    </li>
                </ul>
            </div>
        </div>

    </div>

    <?php include TPL_PATH."/comm/foot.phtml"?>

	<!--登陆弹层-->
	<div class="modal layer-login " style="display:none">
	    <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	        <h4>登录睿助理</h4>
	    </div>
	    <div class="modal-body row-fluid">
	        <div class="span5">
	            <h5>没有账号？请立即申请</h5>
	            <a href="javascript:void(0);" class="btn">立即注册</a>
	        </div>
	        <div class="span7">
	            <form class="form-horizontal">
	                <div class="control-group">
	                    <label class="control-label" for="inputEmail">账号</label>
	                    <div class="controls input-prepend">
	                        <span class="add-on"><i class="icon-user"></i>
	                        </span>
	                        <input class="input-medium" id="prependedInput" type="text" placeholder="邮箱/手机号">
	                    </div>
	                </div>
	                <div class="control-group">
	                    <label class="control-label" for="inputEmail">密码</label>
	                    <div class="controls input-prepend">
	                        <span class="add-on"><i class="icon-lock"></i>
	                        </span>
	                        <input class="input-medium" id="prependedInput" type="text" placeholder="输入您的密码">
	                    </div>
	                </div>
	                <div class="control-group">
	                    <label class="control-label" for="inputEmail"> </label>
	                    <div class="controls box-btn">
	                        <button type="submit" class="btn">登录</button>
	                    </div>
	                </div>
	            </form>
	        </div>
	    </div>
	    <div class="modal-footer">
	        <a href="javascript:void(0);">忘了密码？</a>
	        <span class="divider">|</span>
	        <a href="javascript:void(0);">注册新账号</a>
	        <span class="divider">|</span>
	        <a href="javascript:void(0);">意见反馈</a>
	    </div>
	</div>
	<!--登陆弹层-->
</body>
</html>
