<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
<link rel="stylesheet" type="text/css" href="http://<?=$domain['res']?>/css/module/combine.css">
<link rel="stylesheet" type="text/css" href="http://<?=$domain['res']?>/css/page/home.css">
<meta charset="utf-8" />
<title>P2PBUY</title>
<meta name="description" content="海淘帮手">
<script src="http://<?=$domain['res']?>/js/jquery-1.11.1.min.js"></script>
<script src="http://<?=$domain['res']?>/js/common.js"></script>
<script src="http://<?=$domain['res']?>/js/index.js"></script>
</head>
<body class="P-home">
    <div class="header">
    	<div class="mask"></div>
    	<div class="cover">
        <!--顶部-->
            <div class="top-bar">
                <div class="inner">
                    <div class="login-info">
                    	<?php if($viewer['uid']):?>
                        <!--已登录状态-->
                        <ul class="inline logined">
                            <!-- <li class="message"><a href="" title="我的消息"><i class="icon-envelope icon-white"><em>&#8226;</em></i><span>消息</span></a></li> -->
                            <li class="message"><a href="/order/list" title="我要帮人买"><span>我要帮人买</span></a></li>
                            <li class="message"><a href="/order/myorder" title="我的订单"><span>我的订单</span></a></li>
                            <li class="head-pic"><a href="javascript:void(0);" class="img"><i class="icon-user icon-white"></i><span class="name"><?=$viewer['nick']?></span></a></li>
                        	<li class="message"><a href="/login/logout" title="退出登录"><span>退出登录</span></a></li>
                        </ul>      
                        <!--已登录状态-->
                        <?php else:?>
                        <!--未登录状态-->
                        <ul class="inline unlogin clearfix" style="display:block">
                            <li><a href="/login/login">登录</a></li>
                            <li><a href="javascript:void(0);">注册</a></li>
                            <li><a href="/order/myorder" class="cur">我是买手</a></li>
                        </ul>
                        <!--未登录状态-->
                        <?php endif;?>
                    </div>
                </div>
            </div>
            <!--/顶部-->

        <!--logo-->
        <h1 class="logo"><a href="javascript:void(0);" title="P2PBUY">P2PBUY</a></h1>
        <!--/logo-->

		<div class="slogan">
            <div class="title">最懂你的海外买手</div>
            <div class="subtitle">中国最大的专业海外买手平台</div>
        </div>

        <!--搜索-->
        <div class="search-box" id="search_tool">
        	<div class="search-wrapper"><input type="text" class="search-input" placeholder="您可以直接粘贴海外商品网址或者点击右边上传商品图片" node-type="thirdurl"><!-- <a href="javascript:void(0);" class="nolink"><input type="file" class="file"></a> --><a href="javascript:void(0);" class="submit" title="搜索" action-type="create_order">搜索</a></div>
        </div>
        <!--/搜索-->
		</div>
    </div>

    <div class="main-content">

        <div class="goods-show">
            <h3 class="title"><span>发现喜爱的商品</span><em>跟随旅行者一起逛遍全球</em></h3>
            <div class="content">
                <ul class="inline list-media clearfix">
                    <li class="item">
                        <div class="pic"><a href="javascript:void(0);"><img data-src="" alt="图片" src="http://<?=$domain['res']?>/img/_temp/u44.jpg" width="500" height="334"></a></div>
                        <div class="caption"><a href="#">巴黎折扣村</a></div>
                    </li>
                    <li class="item">
                        <div class="pic"><a href="javascript:void(0);"><img data-src="" alt="图片" src="http://<?=$domain['res']?>/img/_temp/u54.jpg" width="500" height="334"></a></div>
                        <div class="caption"><a href="#">迪拜土豪之都</a></div>
                    </li>
                    <li class="item">
                        <div class="pic"><a href="javascript:void(0);"><img data-src="" alt="图片" src="http://<?=$domain['res']?>/img/_temp/u64.png" width="500" height="334"></a></div>
                        <div class="caption"><a href="#">美国西海岸购物天堂</a></div>
                    </li>
                    <li class="item">
                        <div class="pic"><a href="javascript:void(0);"><img data-src="" alt="图片" src="http://<?=$domain['res']?>/img/_temp/u72.png" width="500" height="334"></a></div>
                        <div class="caption"><a href="#">足不出户购尽天下商品</a></div>
                    </li>
                    <li class="item">
                        <div class="pic"><a href="javascript:void(0);"><img data-src="" alt="图片" src="http://<?=$domain['res']?>/img/_temp/u54.jpg" width="500" height="334"></a></div>
                        <div class="caption"><a href="#">迪拜土豪之都</a></div>
                    </li>
                    <li class="item">
                        <div class="pic"><a href="javascript:void(0);"><img data-src="" alt="图片" src="http://<?=$domain['res']?>/img/_temp/u44.jpg" width="500" height="334"></a></div>
                        <div class="caption"><a href="#">巴黎折扣村</a></div>
                    </li>
                </ul>
            </div>
        </div>

    </div>

    <?php include TPL_PATH."/comm/foot.phtml"?>

	<!--登陆弹层-->
	<div class="modal layer-login " style="display:none">
	    <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	        <h4>登录睿助理</h4>
	    </div>
	    <div class="modal-body row-fluid">
	        <div class="span5">
	            <h5>没有账号？请立即申请</h5>
	            <a href="javascript:void(0);" class="btn">立即注册</a>
	        </div>
	        <div class="span7">
	            <form class="form-horizontal">
	                <div class="control-group">
	                    <label class="control-label" for="inputEmail">账号</label>
	                    <div class="controls input-prepend">
	                        <span class="add-on"><i class="icon-user"></i>
	                        </span>
	                        <input class="input-medium" id="prependedInput" type="text" placeholder="邮箱/手机号">
	                    </div>
	                </div>
	                <div class="control-group">
	                    <label class="control-label" for="inputEmail">密码</label>
	                    <div class="controls input-prepend">
	                        <span class="add-on"><i class="icon-lock"></i>
	                        </span>
	                        <input class="input-medium" id="prependedInput" type="text" placeholder="输入您的密码">
	                    </div>
	                </div>
	                <div class="control-group">
	                    <label class="control-label" for="inputEmail"> </label>
	                    <div class="controls box-btn">
	                        <button type="submit" class="btn">登录</button>
	                    </div>
	                </div>
	            </form>
	        </div>
	    </div>
	    <div class="modal-footer">
	        <a href="javascript:void(0);">忘了密码？</a>
	        <span class="divider">|</span>
	        <a href="javascript:void(0);">注册新账号</a>
	        <span class="divider">|</span>
	        <a href="javascript:void(0);">意见反馈</a>
	    </div>
	</div>
	<!--登陆弹层-->
</body>
</html>
