<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
<link rel="stylesheet" type="text/css" href="http://<?=$domain['res']?>/css/module/combine.css">
<link rel="stylesheet" type="text/css" href="http://<?=$domain['res']?>/css/page/home.css">
<meta charset="utf-8" />
<title>P2PBUY</title>
<meta name="description" content="海淘帮手">
<script src="http://<?=$domain['res']?>/js/jquery-1.11.1.min.js"></script>
<script src="http://<?=$domain['res']?>/js/common.js"></script>
<script src="http://<?=$domain['res']?>/js/transads.js"></script>
</head>
<body class="P-home">
    <div class="header">
    	<div class="mask"></div>
    	<div class="cover">
        <!--顶部-->
            <div class="top-bar">
                <div class="inner">
                    <div class="login-info">
                    	<?php if($viewer['uid']):?>
                        <!--已登录状态-->
                        <ul class="inline logined">
                            <!-- <li class="message"><a href="" title="我的消息"><i class="icon-envelope icon-white"><em>&#8226;</em></i><span>消息</span></a></li> -->
                            <li class="message"><a href="/order/list" title="我要帮人买"><span>我要帮人买</span></a></li>
                            <li class="message"><a href="/order/myorder" title="我的订单"><span>我的订单</span></a></li>
                            <li class="head-pic"><a href="javascript:void(0);" class="img"><i class="icon-user icon-white"></i><span class="name"><?=$viewer['nick']?></span></a></li>
                        	<li class="message"><a href="/login/logout" title="退出登录"><span>退出登录</span></a></li>
                        </ul>      
                        <!--已登录状态-->
                        <?php else:?>
                        <!--未登录状态-->
                        <ul class="inline unlogin clearfix" style="display:block">
                            <li><a href="/login/login">登录</a></li>
                            <li><a href="javascript:void(0);">注册</a></li>
                            <li><a href="/order/myorder" class="cur">我是买手</a></li>
                        </ul>
                        <!--未登录状态-->
                        <?php endif;?>
                    </div>
                </div>
            </div>
            <!--/顶部-->

        <!--logo-->
        <h1 class="logo"><a href="javascript:void(0);" title="P2PBUY">P2PBUY</a></h1>
        <!--/logo-->

		<div class="slogan">
            <div class="title">最懂你的海外买手</div>
            <div class="subtitle">中国最大的专业海外买手平台</div>
        </div>

        <!--生成-->
        <div class="search-box" id="transads_tool">
        	<div class="search-wrapper"><input type="text" class="search-input" placeholder="请填入商品网址" node-type="thirdurl"><!-- <a href="javascript:void(0);" class="nolink"><input type="file" class="file"></a> --><a href="javascript:void(0);" class="submit" title="生成" action-type="create_ads">生成</a></div>
        </div>
        <!--/生成-->
		</div>
    </div>

    <?php include TPL_PATH."/comm/foot.phtml"?>
    
</body>
</html>
