<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>1</title>
</head>
<body>
<form action="/amazontest" method="post">
亚马逊地址：<input name="amazonurl" type="text" /></br>
<input type="hidden" name="action" value="amazon" />
<input type="submit" value="submit" />
</form>
</body>

</html>